/*
 * File: app/store/ApplyLog.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.store.ApplyLog', {
  extend: 'Ext.data.Store',

  requires: [
    'ZJ02.model.ApplyLog'
  ],

  config: {
    data: [
      {
        applyId: 1,
        applyTime: '2014/1/23 16:49:12',
        posName: 'java软件工程师',
        enterpriseName: '上海创驰网络有限公司',
        applyCount: 1
      },
      {
        applyId: 2,
        applyTime: '2014/1/23 16:49:12',
        posName: 'java软件工程师',
        enterpriseName: '上海创驰网络有限公司',
        applyCount: 1
      }
    ],
    model: 'ZJ02.model.ApplyLog',
    storeId: 'ApplyLog'
  }
});