/*
 * File: app/store/Company.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.store.Company', {
  extend: 'Ext.data.Store',

  requires: [
    'ZJ02.model.Company'
  ],

  config: {
    data: [
      {
        companyId: 1,
        companyLogo: 'images/logo_60s_01.png',
        companyName: '上海创驰网络科技有限公司',
        listPosition: [
          {
            positionId: 1,
            positionName: '产品经理',
            companyName: '上海创驰网络科技有限公司',
            companyId: 1,
            salary: '面议',
            refreshiTime: '2014-02-17 16:17:00'
          },
          {
            positionId: 2,
            positionName: '程序员',
            companyName: '上海创驰网络科技有限公司',
            companyId: 1,
            salary: '面议',
            refreshiTime: '2014-02-17 16:17:00'
          }
        ]
      },
      {
        companyId: 2,
        companyLogo: 'images/logo_60s_02.png',
        companyName: '上海创驰网络科技有限公司',
        listPosition: [
          {
            positionId: 1,
            positionName: '产品经理',
            companyName: '上海创驰网络科技有限公司',
            companyId: 1,
            salary: '面议',
            refreshiTime: '2014-02-17 16:17:00'
          },
          {
            positionId: 2,
            positionName: '程序员',
            companyName: '上海创驰网络科技有限公司',
            companyId: 1,
            salary: '面议',
            refreshiTime: '2014-02-17 16:17:00'
          }
        ]
      },
      {
        companyId: 3,
        companyLogo: 'images/logo_60s_03.png',
        companyName: '上海创驰网络科技有限公司',
        listPosition: [
          {
            positionId: 1,
            positionName: '产品经理',
            companyName: '上海创驰网络科技有限公司',
            companyId: 1,
            salary: '面议',
            refreshiTime: '2014-02-17 16:17:00'
          },
          {
            positionId: 2,
            positionName: '程序员',
            companyName: '上海创驰网络科技有限公司',
            companyId: 1,
            salary: '面议',
            refreshiTime: '2014-02-17 16:17:00'
          }
        ]
      }
    ],
    model: 'ZJ02.model.Company',
    storeId: 'Company'
  }
});