/*
 * File: app/store/hpNav.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.store.hpNav', {
  extend: 'Ext.data.Store',

  requires: [
    'ZJ02.model.hpNav'
  ],

  config: {
    data: [
      {
        title: '职位订阅',
        desc: '轻松订阅，好职位来找你',
        target: 'ZJ01.view.PositionBook'
      },
      {
        title: '二维码简历',
        desc: '打造属于自己的二维码简历',
        target: 'ZJ01.view.Resume'
      },
      {
        title: '日程提醒',
        desc: '参加招聘会、宣讲会，日程提醒，轻松面对',
        target: 'ZJ01.view.Notice'
      }
    ],
    model: 'ZJ02.model.hpNav',
    storeId: 'hpNav'
  }
});