/*
 * File: app/store/InterviewNotice.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.store.InterviewNotice', {
  extend: 'Ext.data.Store',

  requires: [
    'ZJ02.model.InterviewNotice'
  ],

  config: {
    data: [
      {
        auditionId: 1,
        companyName: '上海创驰网络科技有限公司',
        positionName: '产品经理',
        auditionContent: '面试通知内容',
        auditionTime: '2014-02-17 16:17:00'
      },
      {
        auditionId: 1,
        companyName: '上海创驰网络科技有限公司',
        positionName: '产品经理',
        auditionContent: '面试通知内容',
        auditionTime: '2014-02-17 16:17:00'
      },
      {
        auditionId: 1,
        companyName: '上海创驰网络科技有限公司',
        positionName: '产品经理',
        auditionContent: '面试通知内容',
        auditionTime: '2014-02-17 16:17:00'
      },
      {
        auditionId: 1,
        companyName: '上海创驰网络科技有限公司',
        positionName: '产品经理',
        auditionContent: '面试通知内容',
        auditionTime: '2014-02-17 16:17:00'
      },
      {
        auditionId: 1,
        companyName: '上海创驰网络科技有限公司',
        positionName: '产品经理',
        auditionContent: '面试通知内容',
        auditionTime: '2014-02-17 16:17:00'
      }
    ],
    model: 'ZJ02.model.InterviewNotice',
    storeId: 'InterviewNotice'
  }
});