/*
 * File: app/store/NestedCitys.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.store.NestedCitys', {
  extend: 'Ext.data.TreeStore',

  requires: [
    'ZJ02.model.NestedData'
  ],

  config: {
    model: 'ZJ02.model.NestedData',
    storeId: 'NestedCitys',
    defaultRootProperty: 'items',
    root: {
      text: '选择城市',
      items: [
        {
          text: '宁夏回族自治区',
          record: {
            areaId: 92,
            areaName: '宁夏回族自治区',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '固原市',
              record: {
                areaId: 1765,
                areaName: '固原市',
                parentId: 92,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '吴忠市',
              record: {
                areaId: 1760,
                areaName: '吴忠市',
                parentId: 92,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '石嘴山市',
              record: {
                areaId: 1782,
                areaName: '石嘴山市',
                parentId: 92,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '银川市',
              record: {
                areaId: 1775,
                areaName: '银川市',
                parentId: 92,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '中卫市',
              record: {
                areaId: 1771,
                areaName: '中卫市',
                parentId: 92,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '新疆维吾尔自治区',
          record: {
            areaId: 95,
            areaName: '新疆维吾尔自治区',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '克拉玛依市',
              record: {
                areaId: 1853,
                areaName: '克拉玛依市',
                parentId: 95,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '克孜勒苏柯尔克孜自治州',
              record: {
                areaId: 1844,
                areaName: '克孜勒苏柯尔克孜自治州',
                parentId: 95,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '阿勒泰地区',
              record: {
                areaId: 1836,
                areaName: '阿勒泰地区',
                parentId: 95,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '和田地区',
              record: {
                areaId: 1827,
                areaName: '和田地区',
                parentId: 95,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '喀什地区',
              record: {
                areaId: 1911,
                areaName: '喀什地区',
                parentId: 95,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '阿克苏地区',
              record: {
                areaId: 1901,
                areaName: '阿克苏地区',
                parentId: 95,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '哈密地区',
              record: {
                areaId: 1883,
                areaName: '哈密地区',
                parentId: 95,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '乌鲁木齐市',
              record: {
                areaId: 1866,
                areaName: '乌鲁木齐市',
                parentId: 95,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '石河子市',
              record: {
                areaId: 1935,
                areaName: '石河子市',
                parentId: 95,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '巴音郭楞蒙古自治州',
              record: {
                areaId: 1891,
                areaName: '巴音郭楞蒙古自治州',
                parentId: 95,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '伊犁哈萨克自治州',
              record: {
                areaId: 1924,
                areaName: '伊犁哈萨克自治州',
                parentId: 95,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '博尔塔拉蒙古自治州',
              record: {
                areaId: 1849,
                areaName: '博尔塔拉蒙古自治州',
                parentId: 95,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '阿拉尔市',
              record: {
                areaId: 1936,
                areaName: '阿拉尔市',
                parentId: 95,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '吐鲁番地区',
              record: {
                areaId: 1887,
                areaName: '吐鲁番地区',
                parentId: 95,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '塔城地区',
              record: {
                areaId: 1875,
                areaName: '塔城地区',
                parentId: 95,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '昌吉回族自治州',
              record: {
                areaId: 1858,
                areaName: '昌吉回族自治州',
                parentId: 95,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '青海省',
          record: {
            areaId: 89,
            areaName: '青海省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '海东地区',
              record: {
                areaId: 508,
                areaName: '海东地区',
                parentId: 89,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '海北藏族自治州',
              record: {
                areaId: 535,
                areaName: '海北藏族自治州',
                parentId: 89,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '海西蒙古族藏族自治州',
              record: {
                areaId: 529,
                areaName: '海西蒙古族藏族自治州',
                parentId: 89,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '西宁市',
              record: {
                areaId: 500,
                areaName: '西宁市',
                parentId: 89,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '海南藏族自治州',
              record: {
                areaId: 545,
                areaName: '海南藏族自治州',
                parentId: 89,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '黄南藏族自治州',
              record: {
                areaId: 540,
                areaName: '黄南藏族自治州',
                parentId: 89,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '玉树藏族自治州',
              record: {
                areaId: 522,
                areaName: '玉树藏族自治州',
                parentId: 89,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '果洛藏族自治州',
              record: {
                areaId: 515,
                areaName: '果洛藏族自治州',
                parentId: 89,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '广西壮族自治区',
          record: {
            areaId: 101,
            areaName: '广西壮族自治区',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '钦州市',
              record: {
                areaId: 3241,
                areaName: '钦州市',
                parentId: 101,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '贺州市',
              record: {
                areaId: 3334,
                areaName: '贺州市',
                parentId: 101,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '北海市',
              record: {
                areaId: 3258,
                areaName: '北海市',
                parentId: 101,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '柳州市',
              record: {
                areaId: 3290,
                areaName: '柳州市',
                parentId: 101,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '防城港市',
              record: {
                areaId: 3271,
                areaName: '防城港市',
                parentId: 101,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '梧州市',
              record: {
                areaId: 3326,
                areaName: '梧州市',
                parentId: 101,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '桂林市',
              record: {
                areaId: 3308,
                areaName: '桂林市',
                parentId: 101,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '来宾市',
              record: {
                areaId: 3301,
                areaName: '来宾市',
                parentId: 101,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '百色市',
              record: {
                areaId: 3352,
                areaName: '百色市',
                parentId: 101,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '玉林市',
              record: {
                areaId: 3345,
                areaName: '玉林市',
                parentId: 101,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '贵港市',
              record: {
                areaId: 3339,
                areaName: '贵港市',
                parentId: 101,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '南宁市',
              record: {
                areaId: 3276,
                areaName: '南宁市',
                parentId: 101,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '崇左市',
              record: {
                areaId: 3263,
                areaName: '崇左市',
                parentId: 101,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '河池市',
              record: {
                areaId: 3246,
                areaName: '河池市',
                parentId: 101,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '广东省',
          record: {
            areaId: 9,
            areaName: '广东省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '中山市',
              record: {
                areaId: 1410,
                areaName: '中山市',
                parentId: 9,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '茂名市',
              record: {
                areaId: 1458,
                areaName: '茂名市',
                parentId: 9,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '潮州市',
              record: {
                areaId: 1434,
                areaName: '潮州市',
                parentId: 9,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '湛江市',
              record: {
                areaId: 1400,
                areaName: '湛江市',
                parentId: 9,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '肇庆市',
              record: {
                areaId: 1391,
                areaName: '肇庆市',
                parentId: 9,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '汕头市',
              record: {
                areaId: 1366,
                areaName: '汕头市',
                parentId: 9,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '广州市',
              record: {
                areaId: 10,
                areaName: '广州市',
                parentId: 9,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '揭阳市',
              record: {
                areaId: 1452,
                areaName: '揭阳市',
                parentId: 9,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '阳江市',
              record: {
                areaId: 1447,
                areaName: '阳江市',
                parentId: 9,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '汕尾市',
              record: {
                areaId: 1442,
                areaName: '汕尾市',
                parentId: 9,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '东莞市',
              record: {
                areaId: 1439,
                areaName: '东莞市',
                parentId: 9,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '云浮市',
              record: {
                areaId: 1428,
                areaName: '云浮市',
                parentId: 9,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '佛山市',
              record: {
                areaId: 1385,
                areaName: '佛山市',
                parentId: 9,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '珠海市',
              record: {
                areaId: 1381,
                areaName: '珠海市',
                parentId: 9,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '深圳市',
              record: {
                areaId: 1374,
                areaName: '深圳市',
                parentId: 9,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '梅州市',
              record: {
                areaId: 1357,
                areaName: '梅州市',
                parentId: 9,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '惠州市',
              record: {
                areaId: 1351,
                areaName: '惠州市',
                parentId: 9,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '韶关市',
              record: {
                areaId: 1340,
                areaName: '韶关市',
                parentId: 9,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '江门市',
              record: {
                areaId: 1332,
                areaName: '江门市',
                parentId: 9,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '清远市',
              record: {
                areaId: 1419,
                areaName: '清远市',
                parentId: 9,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '河源市',
              record: {
                areaId: 1412,
                areaName: '河源市',
                parentId: 9,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '上海市',
          record: {
            areaId: 1,
            areaName: '上海市',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '上海市',
              record: {
                areaId: 2,
                areaName: '上海市',
                parentId: 1,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '山东省',
          record: {
            areaId: 56,
            areaName: '山东省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '泰安市',
              record: {
                areaId: 3178,
                areaName: '泰安市',
                parentId: 56,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '淄博市',
              record: {
                areaId: 3118,
                areaName: '淄博市',
                parentId: 56,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '威海市',
              record: {
                areaId: 3212,
                areaName: '威海市',
                parentId: 56,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '潍坊市',
              record: {
                areaId: 3152,
                areaName: '潍坊市',
                parentId: 56,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '德州市',
              record: {
                areaId: 3127,
                areaName: '德州市',
                parentId: 56,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '烟台市',
              record: {
                areaId: 3139,
                areaName: '烟台市',
                parentId: 56,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '青岛市',
              record: {
                areaId: 3105,
                areaName: '青岛市',
                parentId: 56,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '济南市',
              record: {
                areaId: 3094,
                areaName: '济南市',
                parentId: 56,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '菏泽市',
              record: {
                areaId: 3084,
                areaName: '菏泽市',
                parentId: 56,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '济宁市',
              record: {
                areaId: 3165,
                areaName: '济宁市',
                parentId: 56,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '聊城市',
              record: {
                areaId: 3232,
                areaName: '聊城市',
                parentId: 56,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '莱芜市',
              record: {
                areaId: 3229,
                areaName: '莱芜市',
                parentId: 56,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '日照市',
              record: {
                areaId: 3224,
                areaName: '日照市',
                parentId: 56,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '枣庄市',
              record: {
                areaId: 3217,
                areaName: '枣庄市',
                parentId: 56,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '东营市',
              record: {
                areaId: 3206,
                areaName: '东营市',
                parentId: 56,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '滨州市',
              record: {
                areaId: 3198,
                areaName: '滨州市',
                parentId: 56,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '临沂市',
              record: {
                areaId: 3185,
                areaName: '临沂市',
                parentId: 56,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '湖南省',
          record: {
            areaId: 65,
            areaName: '湖南省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '张家界市',
              record: {
                areaId: 754,
                areaName: '张家界市',
                parentId: 65,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '湘西土家族苗族自治州',
              record: {
                areaId: 745,
                areaName: '湘西土家族苗族自治州',
                parentId: 65,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '永州市',
              record: {
                areaId: 772,
                areaName: '永州市',
                parentId: 65,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '怀化市',
              record: {
                areaId: 759,
                areaName: '怀化市',
                parentId: 65,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '娄底市',
              record: {
                areaId: 726,
                areaName: '娄底市',
                parentId: 65,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '常德市',
              record: {
                areaId: 709,
                areaName: '常德市',
                parentId: 65,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '衡阳市',
              record: {
                areaId: 684,
                areaName: '衡阳市',
                parentId: 65,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '长沙市',
              record: {
                areaId: 658,
                areaName: '长沙市',
                parentId: 65,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '岳阳市',
              record: {
                areaId: 648,
                areaName: '岳阳市',
                parentId: 65,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '邵阳市',
              record: {
                areaId: 732,
                areaName: '邵阳市',
                parentId: 65,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '益阳市',
              record: {
                areaId: 719,
                areaName: '益阳市',
                parentId: 65,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '郴州市',
              record: {
                areaId: 697,
                areaName: '郴州市',
                parentId: 65,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '株洲市',
              record: {
                areaId: 674,
                areaName: '株洲市',
                parentId: 65,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '湘潭市',
              record: {
                areaId: 668,
                areaName: '湘潭市',
                parentId: 65,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '河南省',
          record: {
            areaId: 59,
            areaName: '河南省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '漯河市',
              record: {
                areaId: 1491,
                areaName: '漯河市',
                parentId: 59,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '郑州市',
              record: {
                areaId: 1553,
                areaName: '郑州市',
                parentId: 59,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '濮阳市',
              record: {
                areaId: 1473,
                areaName: '濮阳市',
                parentId: 59,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '南阳市',
              record: {
                areaId: 1618,
                areaName: '南阳市',
                parentId: 59,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '平顶山市',
              record: {
                areaId: 1596,
                areaName: '平顶山市',
                parentId: 59,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '周口市',
              record: {
                areaId: 1480,
                areaName: '周口市',
                parentId: 59,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '鹤壁市',
              record: {
                areaId: 1467,
                areaName: '鹤壁市',
                parentId: 59,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '商丘市',
              record: {
                areaId: 1543,
                areaName: '商丘市',
                parentId: 59,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '济源市',
              record: {
                areaId: 1542,
                areaName: '济源市',
                parentId: 59,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '焦作市',
              record: {
                areaId: 1531,
                areaName: '焦作市',
                parentId: 59,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '洛阳市',
              record: {
                areaId: 1515,
                areaName: '洛阳市',
                parentId: 59,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '信阳市',
              record: {
                areaId: 1607,
                areaName: '信阳市',
                parentId: 59,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '许昌市',
              record: {
                areaId: 1589,
                areaName: '许昌市',
                parentId: 59,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '新乡市',
              record: {
                areaId: 1576,
                areaName: '新乡市',
                parentId: 59,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '安阳市',
              record: {
                areaId: 1566,
                areaName: '安阳市',
                parentId: 59,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '开封市',
              record: {
                areaId: 1632,
                areaName: '开封市',
                parentId: 59,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '三门峡市',
              record: {
                areaId: 1508,
                areaName: '三门峡市',
                parentId: 59,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '驻马店市',
              record: {
                areaId: 1497,
                areaName: '驻马店市',
                parentId: 59,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '江西省',
          record: {
            areaId: 53,
            areaName: '江西省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '吉安市',
              record: {
                areaId: 2140,
                areaName: '吉安市',
                parentId: 53,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '南昌市',
              record: {
                areaId: 2191,
                areaName: '南昌市',
                parentId: 53,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '九江市',
              record: {
                areaId: 2201,
                areaName: '九江市',
                parentId: 53,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '萍乡市',
              record: {
                areaId: 2178,
                areaName: '萍乡市',
                parentId: 53,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '新余市',
              record: {
                areaId: 2188,
                areaName: '新余市',
                parentId: 53,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '鹰潭市',
              record: {
                areaId: 2184,
                areaName: '鹰潭市',
                parentId: 53,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '景德镇市',
              record: {
                areaId: 2173,
                areaName: '景德镇市',
                parentId: 53,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '赣州市',
              record: {
                areaId: 2154,
                areaName: '赣州市',
                parentId: 53,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '宜春市',
              record: {
                areaId: 2239,
                areaName: '宜春市',
                parentId: 53,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '抚州市',
              record: {
                areaId: 2227,
                areaName: '抚州市',
                parentId: 53,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '上饶市',
              record: {
                areaId: 2214,
                areaName: '上饶市',
                parentId: 53,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '福建省',
          record: {
            areaId: 50,
            areaName: '福建省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '福州市',
              record: {
                areaId: 784,
                areaName: '福州市',
                parentId: 50,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '厦门市',
              record: {
                areaId: 798,
                areaName: '厦门市',
                parentId: 50,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '漳州市',
              record: {
                areaId: 834,
                areaName: '漳州市',
                parentId: 50,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '泉州市',
              record: {
                areaId: 821,
                areaName: '泉州市',
                parentId: 50,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '南平市',
              record: {
                areaId: 867,
                areaName: '南平市',
                parentId: 50,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '三明市',
              record: {
                areaId: 854,
                areaName: '三明市',
                parentId: 50,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '龙岩市',
              record: {
                areaId: 846,
                areaName: '龙岩市',
                parentId: 50,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '莆田市',
              record: {
                areaId: 815,
                areaName: '莆田市',
                parentId: 50,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '宁德市',
              record: {
                areaId: 805,
                areaName: '宁德市',
                parentId: 50,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '安徽省',
          record: {
            areaId: 47,
            areaName: '安徽省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '马鞍山市',
              record: {
                areaId: 3550,
                areaName: '马鞍山市',
                parentId: 47,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '淮北市',
              record: {
                areaId: 3595,
                areaName: '淮北市',
                parentId: 47,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '亳州市',
              record: {
                areaId: 3582,
                areaName: '亳州市',
                parentId: 47,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '阜阳市',
              record: {
                areaId: 3573,
                areaName: '阜阳市',
                parentId: 47,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '六安市',
              record: {
                areaId: 3613,
                areaName: '六安市',
                parentId: 47,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '宣城市',
              record: {
                areaId: 3605,
                areaName: '宣城市',
                parentId: 47,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '铜陵市',
              record: {
                areaId: 3600,
                areaName: '铜陵市',
                parentId: 47,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '黄山市',
              record: {
                areaId: 3587,
                areaName: '黄山市',
                parentId: 47,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '宿州市',
              record: {
                areaId: 3567,
                areaName: '宿州市',
                parentId: 47,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '安庆市',
              record: {
                areaId: 3555,
                areaName: '安庆市',
                parentId: 47,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '淮南市',
              record: {
                areaId: 3543,
                areaName: '淮南市',
                parentId: 47,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '芜湖市',
              record: {
                areaId: 3535,
                areaName: '芜湖市',
                parentId: 47,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '蚌埠市',
              record: {
                areaId: 3527,
                areaName: '蚌埠市',
                parentId: 47,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '滁州市',
              record: {
                areaId: 3518,
                areaName: '滁州市',
                parentId: 47,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '合肥市',
              record: {
                areaId: 3510,
                areaName: '合肥市',
                parentId: 47,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '池州市',
              record: {
                areaId: 3627,
                areaName: '池州市',
                parentId: 47,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '浙江省',
          record: {
            areaId: 44,
            areaName: '浙江省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '宁波市',
              record: {
                areaId: 1147,
                areaName: '宁波市',
                parentId: 44,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '台州市',
              record: {
                areaId: 138,
                areaName: '台州市',
                parentId: 44,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '舟山市',
              record: {
                areaId: 137,
                areaName: '舟山市',
                parentId: 44,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '衢州市',
              record: {
                areaId: 136,
                areaName: '衢州市',
                parentId: 44,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '金华市',
              record: {
                areaId: 135,
                areaName: '金华市',
                parentId: 44,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '绍兴市',
              record: {
                areaId: 134,
                areaName: '绍兴市',
                parentId: 44,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '湖州市',
              record: {
                areaId: 133,
                areaName: '湖州市',
                parentId: 44,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '嘉兴市',
              record: {
                areaId: 132,
                areaName: '嘉兴市',
                parentId: 44,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '温州市',
              record: {
                areaId: 131,
                areaName: '温州市',
                parentId: 44,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '杭州市',
              record: {
                areaId: 130,
                areaName: '杭州市',
                parentId: 44,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '丽水市',
              record: {
                areaId: 139,
                areaName: '丽水市',
                parentId: 44,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '江苏省',
          record: {
            areaId: 41,
            areaName: '江苏省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '南京市',
              record: {
                areaId: 116,
                areaName: '南京市',
                parentId: 41,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '南通市',
              record: {
                areaId: 128,
                areaName: '南通市',
                parentId: 41,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '镇江市',
              record: {
                areaId: 124,
                areaName: '镇江市',
                parentId: 41,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '泰州市',
              record: {
                areaId: 123,
                areaName: '泰州市',
                parentId: 41,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '扬州市',
              record: {
                areaId: 122,
                areaName: '扬州市',
                parentId: 41,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '盐城市',
              record: {
                areaId: 121,
                areaName: '盐城市',
                parentId: 41,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '淮安市',
              record: {
                areaId: 120,
                areaName: '淮安市',
                parentId: 41,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '宿迁市',
              record: {
                areaId: 119,
                areaName: '宿迁市',
                parentId: 41,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '连云港市',
              record: {
                areaId: 118,
                areaName: '连云港市',
                parentId: 41,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '徐州市',
              record: {
                areaId: 117,
                areaName: '徐州市',
                parentId: 41,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '苏州市',
              record: {
                areaId: 127,
                areaName: '苏州市',
                parentId: 41,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '无锡市',
              record: {
                areaId: 126,
                areaName: '无锡市',
                parentId: 41,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '常州市',
              record: {
                areaId: 125,
                areaName: '常州市',
                parentId: 41,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '黑龙江省',
          record: {
            areaId: 35,
            areaName: '黑龙江省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '大庆市',
              record: {
                areaId: 3467,
                areaName: '大庆市',
                parentId: 35,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '佳木斯市',
              record: {
                areaId: 3412,
                areaName: '佳木斯市',
                parentId: 35,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '齐齐哈尔市',
              record: {
                areaId: 3384,
                areaName: '齐齐哈尔市',
                parentId: 35,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '哈尔滨市',
              record: {
                areaId: 3365,
                areaName: '哈尔滨市',
                parentId: 35,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '双鸭山市',
              record: {
                areaId: 3501,
                areaName: '双鸭山市',
                parentId: 35,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '鹤岗市',
              record: {
                areaId: 3492,
                areaName: '鹤岗市',
                parentId: 35,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '七台河市',
              record: {
                areaId: 3477,
                areaName: '七台河市',
                parentId: 35,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '伊春市',
              record: {
                areaId: 3449,
                areaName: '伊春市',
                parentId: 35,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '大兴安岭地区',
              record: {
                areaId: 3441,
                areaName: '大兴安岭地区',
                parentId: 35,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '黑河市',
              record: {
                areaId: 3434,
                areaName: '黑河市',
                parentId: 35,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '绥化市',
              record: {
                areaId: 3423,
                areaName: '绥化市',
                parentId: 35,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '牡丹江市',
              record: {
                areaId: 3401,
                areaName: '牡丹江市',
                parentId: 35,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '鸡西市',
              record: {
                areaId: 3482,
                areaName: '鸡西市',
                parentId: 35,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '吉林省',
          record: {
            areaId: 32,
            areaName: '吉林省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '辽源市',
              record: {
                areaId: 3066,
                areaName: '辽源市',
                parentId: 32,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '长春市',
              record: {
                areaId: 3015,
                areaName: '长春市',
                parentId: 32,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '白山市',
              record: {
                areaId: 3077,
                areaName: '白山市',
                parentId: 32,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '松原市',
              record: {
                areaId: 3071,
                areaName: '松原市',
                parentId: 32,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '白城市',
              record: {
                areaId: 3060,
                areaName: '白城市',
                parentId: 32,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '通化市',
              record: {
                areaId: 3052,
                areaName: '通化市',
                parentId: 32,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '四平市',
              record: {
                areaId: 3045,
                areaName: '四平市',
                parentId: 32,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '延边朝鲜族自治州',
              record: {
                areaId: 3036,
                areaName: '延边朝鲜族自治州',
                parentId: 32,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '吉林市',
              record: {
                areaId: 3026,
                areaName: '吉林市',
                parentId: 32,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '辽宁省',
          record: {
            areaId: 29,
            areaName: '辽宁省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '锦州市',
              record: {
                areaId: 2493,
                areaName: '锦州市',
                parentId: 29,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '盘锦市',
              record: {
                areaId: 2532,
                areaName: '盘锦市',
                parentId: 29,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '铁岭市',
              record: {
                areaId: 2558,
                areaName: '铁岭市',
                parentId: 29,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '大连市',
              record: {
                areaId: 2566,
                areaName: '大连市',
                parentId: 29,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '沈阳市',
              record: {
                areaId: 2544,
                areaName: '沈阳市',
                parentId: 29,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '葫芦岛市',
              record: {
                areaId: 2537,
                areaName: '葫芦岛市',
                parentId: 29,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '朝阳市',
              record: {
                areaId: 2524,
                areaName: '朝阳市',
                parentId: 29,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '辽阳市',
              record: {
                areaId: 2516,
                areaName: '辽阳市',
                parentId: 29,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '鞍山市',
              record: {
                areaId: 2577,
                areaName: '鞍山市',
                parentId: 29,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '阜新市',
              record: {
                areaId: 2508,
                areaName: '阜新市',
                parentId: 29,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '营口市',
              record: {
                areaId: 2501,
                areaName: '营口市',
                parentId: 29,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '丹东市',
              record: {
                areaId: 2486,
                areaName: '丹东市',
                parentId: 29,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '本溪市',
              record: {
                areaId: 2479,
                areaName: '本溪市',
                parentId: 29,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '抚顺市',
              record: {
                areaId: 2471,
                areaName: '抚顺市',
                parentId: 29,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '内蒙古自治区',
          record: {
            areaId: 26,
            areaName: '内蒙古自治区',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '阿拉善盟',
              record: {
                areaId: 2694,
                areaName: '阿拉善盟',
                parentId: 26,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '赤峰市',
              record: {
                areaId: 2644,
                areaName: '赤峰市',
                parentId: 26,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '乌兰察布市',
              record: {
                areaId: 2623,
                areaName: '乌兰察布市',
                parentId: 26,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '呼和浩特市',
              record: {
                areaId: 2599,
                areaName: '呼和浩特市',
                parentId: 26,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '锡林郭勒盟',
              record: {
                areaId: 2674,
                areaName: '锡林郭勒盟',
                parentId: 26,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '巴彦淖尔市',
              record: {
                areaId: 2666,
                areaName: '巴彦淖尔市',
                parentId: 26,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '鄂尔多斯市',
              record: {
                areaId: 2657,
                areaName: '鄂尔多斯市',
                parentId: 26,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '通辽市',
              record: {
                areaId: 2635,
                areaName: '通辽市',
                parentId: 26,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '乌海市',
              record: {
                areaId: 2619,
                areaName: '乌海市',
                parentId: 26,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '包头市',
              record: {
                areaId: 2609,
                areaName: '包头市',
                parentId: 26,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '呼伦贝尔市',
              record: {
                areaId: 2585,
                areaName: '呼伦贝尔市',
                parentId: 26,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '兴安盟',
              record: {
                areaId: 2687,
                areaName: '兴安盟',
                parentId: 26,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '山西省',
          record: {
            areaId: 23,
            areaName: '山西省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '朔州市',
              record: {
                areaId: 2330,
                areaName: '朔州市',
                parentId: 23,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '吕梁市',
              record: {
                areaId: 2432,
                areaName: '吕梁市',
                parentId: 23,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '临汾市',
              record: {
                areaId: 2414,
                areaName: '临汾市',
                parentId: 23,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '晋城市',
              record: {
                areaId: 2407,
                areaName: '晋城市',
                parentId: 23,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '运城市',
              record: {
                areaId: 2446,
                areaName: '运城市',
                parentId: 23,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '长治市',
              record: {
                areaId: 2393,
                areaName: '长治市',
                parentId: 23,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '晋中市',
              record: {
                areaId: 2381,
                areaName: '晋中市',
                parentId: 23,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '阳泉市',
              record: {
                areaId: 2375,
                areaName: '阳泉市',
                parentId: 23,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '大同市',
              record: {
                areaId: 2363,
                areaName: '大同市',
                parentId: 23,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '太原市',
              record: {
                areaId: 2352,
                areaName: '太原市',
                parentId: 23,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '忻州市',
              record: {
                areaId: 2337,
                areaName: '忻州市',
                parentId: 23,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '河北省',
          record: {
            areaId: 20,
            areaName: '河北省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '衡水市',
              record: {
                areaId: 2082,
                areaName: '衡水市',
                parentId: 20,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '张家口市',
              record: {
                areaId: 2009,
                areaName: '张家口市',
                parentId: 20,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '唐山市',
              record: {
                areaId: 2039,
                areaName: '唐山市',
                parentId: 20,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '邯郸市',
              record: {
                areaId: 1939,
                areaName: '邯郸市',
                parentId: 20,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '沧州市',
              record: {
                areaId: 2065,
                areaName: '沧州市',
                parentId: 20,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '廊坊市',
              record: {
                areaId: 2054,
                areaName: '廊坊市',
                parentId: 20,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '承德市',
              record: {
                areaId: 2027,
                areaName: '承德市',
                parentId: 20,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '保定市',
              record: {
                areaId: 1983,
                areaName: '保定市',
                parentId: 20,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '石家庄市',
              record: {
                areaId: 1959,
                areaName: '石家庄市',
                parentId: 20,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '秦皇岛市',
              record: {
                areaId: 2114,
                areaName: '秦皇岛市',
                parentId: 20,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '邢台市',
              record: {
                areaId: 2094,
                areaName: '邢台市',
                parentId: 20,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '天津市',
          record: {
            areaId: 17,
            areaName: '天津市',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '天津市',
              record: {
                areaId: 18,
                areaName: '天津市',
                parentId: 17,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '湖北省',
          record: {
            areaId: 62,
            areaName: '湖北省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '十堰市',
              record: {
                areaId: 2924,
                areaName: '十堰市',
                parentId: 62,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '襄阳市',
              record: {
                areaId: 3854,
                areaName: '襄阳市',
                parentId: 62,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '鄂州市',
              record: {
                areaId: 2978,
                areaName: '鄂州市',
                parentId: 62,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '仙桃市',
              record: {
                areaId: 2942,
                areaName: '仙桃市',
                parentId: 62,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '随州市',
              record: {
                areaId: 2933,
                areaName: '随州市',
                parentId: 62,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '宜昌市',
              record: {
                areaId: 2910,
                areaName: '宜昌市',
                parentId: 62,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '荆州市',
              record: {
                areaId: 2901,
                areaName: '荆州市',
                parentId: 62,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '咸宁市',
              record: {
                areaId: 3008,
                areaName: '咸宁市',
                parentId: 62,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '黄石市',
              record: {
                areaId: 3001,
                areaName: '黄石市',
                parentId: 62,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '黄冈市',
              record: {
                areaId: 2990,
                areaName: '黄冈市',
                parentId: 62,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '孝感市',
              record: {
                areaId: 2982,
                areaName: '孝感市',
                parentId: 62,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '襄樊市',
              record: {
                areaId: 2968,
                areaName: '襄樊市',
                parentId: 62,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '武汉市',
              record: {
                areaId: 2954,
                areaName: '武汉市',
                parentId: 62,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '恩施土家族苗族自治州',
              record: {
                areaId: 2945,
                areaName: '恩施土家族苗族自治州',
                parentId: 62,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '天门市',
              record: {
                areaId: 2944,
                areaName: '天门市',
                parentId: 62,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '潜江市',
              record: {
                areaId: 2943,
                areaName: '潜江市',
                parentId: 62,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '荆门市',
              record: {
                areaId: 2936,
                areaName: '荆门市',
                parentId: 62,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '北京市',
          record: {
            areaId: 5,
            areaName: '北京市',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '北京市',
              record: {
                areaId: 6,
                areaName: '北京市',
                parentId: 5,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '甘肃省',
          record: {
            areaId: 86,
            areaName: '甘肃省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '庆阳市',
              record: {
                areaId: 1233,
                areaName: '庆阳市',
                parentId: 86,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '甘南藏族自治州',
              record: {
                areaId: 1291,
                areaName: '甘南藏族自治州',
                parentId: 86,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '嘉峪关市',
              record: {
                areaId: 1281,
                areaName: '嘉峪关市',
                parentId: 86,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '酒泉市',
              record: {
                areaId: 1256,
                areaName: '酒泉市',
                parentId: 86,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '平凉市',
              record: {
                areaId: 1225,
                areaName: '平凉市',
                parentId: 86,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '陇南市',
              record: {
                areaId: 1207,
                areaName: '陇南市',
                parentId: 86,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '定西市',
              record: {
                areaId: 1217,
                areaName: '定西市',
                parentId: 86,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '白银市',
              record: {
                areaId: 1300,
                areaName: '白银市',
                parentId: 86,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '张掖市',
              record: {
                areaId: 1249,
                areaName: '张掖市',
                parentId: 86,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '临夏回族自治州',
              record: {
                areaId: 1282,
                areaName: '临夏回族自治州',
                parentId: 86,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '兰州市',
              record: {
                areaId: 1272,
                areaName: '兰州市',
                parentId: 86,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '天水市',
              record: {
                areaId: 1264,
                areaName: '天水市',
                parentId: 86,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '武威市',
              record: {
                areaId: 1244,
                areaName: '武威市',
                parentId: 86,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '金昌市',
              record: {
                areaId: 1241,
                areaName: '金昌市',
                parentId: 86,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '陕西省',
          record: {
            areaId: 83,
            areaName: '陕西省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '榆林市',
              record: {
                areaId: 1691,
                areaName: '榆林市',
                parentId: 83,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '汉中市',
              record: {
                areaId: 1735,
                areaName: '汉中市',
                parentId: 83,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '安康市',
              record: {
                areaId: 1724,
                areaName: '安康市',
                parentId: 83,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '渭南市',
              record: {
                areaId: 1704,
                areaName: '渭南市',
                parentId: 83,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '宝鸡市',
              record: {
                areaId: 1747,
                areaName: '宝鸡市',
                parentId: 83,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '铜川市',
              record: {
                areaId: 1643,
                areaName: '铜川市',
                parentId: 83,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '延安市',
              record: {
                areaId: 1677,
                areaName: '延安市',
                parentId: 83,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '咸阳市',
              record: {
                areaId: 1662,
                areaName: '咸阳市',
                parentId: 83,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '西安市',
              record: {
                areaId: 1648,
                areaName: '西安市',
                parentId: 83,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '商洛市',
              record: {
                areaId: 1716,
                areaName: '商洛市',
                parentId: 83,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '西藏自治区',
          record: {
            areaId: 80,
            areaName: '西藏自治区',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '拉萨市',
              record: {
                areaId: 2250,
                areaName: '拉萨市',
                parentId: 80,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '云南省',
          record: {
            areaId: 77,
            areaName: '云南省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '西双版纳傣族自治州',
              record: {
                areaId: 1119,
                areaName: '西双版纳傣族自治州',
                parentId: 77,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '昆明市',
              record: {
                areaId: 984,
                areaName: '昆明市',
                parentId: 77,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '昭通市',
              record: {
                areaId: 999,
                areaName: '昭通市',
                parentId: 77,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '普洱市',
              record: {
                areaId: 1084,
                areaName: '普洱市',
                parentId: 77,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '楚雄彝族自治州',
              record: {
                areaId: 1073,
                areaName: '楚雄彝族自治州',
                parentId: 77,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '文山壮族苗族自治州',
              record: {
                areaId: 1054,
                areaName: '文山壮族苗族自治州',
                parentId: 77,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '保山市',
              record: {
                areaId: 1048,
                areaName: '保山市',
                parentId: 77,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '临沧市',
              record: {
                areaId: 1095,
                areaName: '临沧市',
                parentId: 77,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '玉溪市',
              record: {
                areaId: 1063,
                areaName: '玉溪市',
                parentId: 77,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '曲靖市',
              record: {
                areaId: 1038,
                areaName: '曲靖市',
                parentId: 77,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '丽江市',
              record: {
                areaId: 1113,
                areaName: '丽江市',
                parentId: 77,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '迪庆藏族自治州',
              record: {
                areaId: 1109,
                areaName: '迪庆藏族自治州',
                parentId: 77,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '怒江傈僳族自治州',
              record: {
                areaId: 1104,
                areaName: '怒江傈僳族自治州',
                parentId: 77,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '红河哈尼族彝族自治州',
              record: {
                areaId: 1024,
                areaName: '红河哈尼族彝族自治州',
                parentId: 77,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '大理白族自治州',
              record: {
                areaId: 1011,
                areaName: '大理白族自治州',
                parentId: 77,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '德宏傣族景颇族自治州',
              record: {
                areaId: 1123,
                areaName: '德宏傣族景颇族自治州',
                parentId: 77,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '贵州省',
          record: {
            areaId: 74,
            areaName: '贵州省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '安顺市',
              record: {
                areaId: 577,
                areaName: '安顺市',
                parentId: 74,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '黔西南布依族苗族自治州',
              record: {
                areaId: 639,
                areaName: '黔西南布依族苗族自治州',
                parentId: 74,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '贵阳市',
              record: {
                areaId: 551,
                areaName: '贵阳市',
                parentId: 74,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '毕节地区',
              record: {
                areaId: 625,
                areaName: '毕节地区',
                parentId: 74,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '六盘水市',
              record: {
                areaId: 634,
                areaName: '六盘水市',
                parentId: 74,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '铜仁地区',
              record: {
                areaId: 614,
                areaName: '铜仁地区',
                parentId: 74,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '黔东南苗族侗族自治州',
              record: {
                areaId: 597,
                areaName: '黔东南苗族侗族自治州',
                parentId: 74,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '黔南布依族苗族自治州',
              record: {
                areaId: 584,
                areaName: '黔南布依族苗族自治州',
                parentId: 74,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '遵义市',
              record: {
                areaId: 562,
                areaName: '遵义市',
                parentId: 74,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '四川省',
          record: {
            areaId: 71,
            areaName: '四川省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '德阳市',
              record: {
                areaId: 2867,
                areaName: '德阳市',
                parentId: 71,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '泸州市',
              record: {
                areaId: 2776,
                areaName: '泸州市',
                parentId: 71,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '甘孜藏族自治州',
              record: {
                areaId: 2882,
                areaName: '甘孜藏族自治州',
                parentId: 71,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '广元市',
              record: {
                areaId: 2874,
                areaName: '广元市',
                parentId: 71,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '凉山彝族自治州',
              record: {
                areaId: 2826,
                areaName: '凉山彝族自治州',
                parentId: 71,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '乐山市',
              record: {
                areaId: 2806,
                areaName: '乐山市',
                parentId: 71,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '资阳市',
              record: {
                areaId: 2801,
                areaName: '资阳市',
                parentId: 71,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '内江市',
              record: {
                areaId: 2795,
                areaName: '内江市',
                parentId: 71,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '宜宾市',
              record: {
                areaId: 2784,
                areaName: '宜宾市',
                parentId: 71,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '广安市',
              record: {
                areaId: 2765,
                areaName: '广安市',
                parentId: 71,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '遂宁市',
              record: {
                areaId: 2759,
                areaName: '遂宁市',
                parentId: 71,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '绵阳市',
              record: {
                areaId: 2731,
                areaName: '绵阳市',
                parentId: 71,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '自贡市',
              record: {
                areaId: 2724,
                areaName: '自贡市',
                parentId: 71,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '攀枝花市',
              record: {
                areaId: 2718,
                areaName: '攀枝花市',
                parentId: 71,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '成都市',
              record: {
                areaId: 2698,
                areaName: '成都市',
                parentId: 71,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '阿坝藏族羌族自治州',
              record: {
                areaId: 2853,
                areaName: '阿坝藏族羌族自治州',
                parentId: 71,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '雅安市',
              record: {
                areaId: 2844,
                areaName: '雅安市',
                parentId: 71,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '眉山市',
              record: {
                areaId: 2818,
                areaName: '眉山市',
                parentId: 71,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '巴中市',
              record: {
                areaId: 2771,
                areaName: '巴中市',
                parentId: 71,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '达州市',
              record: {
                areaId: 2751,
                areaName: '达州市',
                parentId: 71,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '南充市',
              record: {
                areaId: 2741,
                areaName: '南充市',
                parentId: 71,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '重庆市',
          record: {
            areaId: 68,
            areaName: '重庆市',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '重庆市',
              record: {
                areaId: 69,
                areaName: '重庆市',
                parentId: 68,
                areaType: 2
              },
              leaf: true
            }
          ]
        },
        {
          text: '海南省',
          record: {
            areaId: 104,
            areaName: '海南省',
            parentId: 0,
            areaType: 1
          },
          items: [
            {
              text: '三亚市',
              record: {
                areaId: 2464,
                areaName: '三亚市',
                parentId: 104,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '西沙群岛',
              record: {
                areaId: 4191,
                areaName: '西沙群岛',
                parentId: 104,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '南沙群岛',
              record: {
                areaId: 4187,
                areaName: '南沙群岛',
                parentId: 104,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '临高县',
              record: {
                areaId: 4210,
                areaName: '临高县',
                parentId: 104,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '定安县',
              record: {
                areaId: 4208,
                areaName: '定安县',
                parentId: 104,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '澄迈县',
              record: {
                areaId: 4204,
                areaName: '澄迈县',
                parentId: 104,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '白沙黎族自治县',
              record: {
                areaId: 3907,
                areaName: '白沙黎族自治县',
                parentId: 104,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '昌江黎族自治县',
              record: {
                areaId: 3890,
                areaName: '昌江黎族自治县',
                parentId: 104,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '陵水黎族自治县',
              record: {
                areaId: 3813,
                areaName: '陵水黎族自治县',
                parentId: 104,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '中沙群岛的岛礁及其海域',
              record: {
                areaId: 4193,
                areaName: '中沙群岛的岛礁及其海域',
                parentId: 104,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '保亭黎族苗族自治县',
              record: {
                areaId: 4183,
                areaName: '保亭黎族苗族自治县',
                parentId: 104,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '琼中黎族苗族自治县',
              record: {
                areaId: 4143,
                areaName: '琼中黎族苗族自治县',
                parentId: 104,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '乐东黎族自治县',
              record: {
                areaId: 4122,
                areaName: '乐东黎族自治县',
                parentId: 104,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '屯昌县',
              record: {
                areaId: 3876,
                areaName: '屯昌县',
                parentId: 104,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '海口市',
              record: {
                areaId: 2459,
                areaName: '海口市',
                parentId: 104,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '万宁市',
              record: {
                areaId: 2469,
                areaName: '万宁市',
                parentId: 104,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '儋州市',
              record: {
                areaId: 2467,
                areaName: '儋州市',
                parentId: 104,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '东方市',
              record: {
                areaId: 2470,
                areaName: '东方市',
                parentId: 104,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '文昌市',
              record: {
                areaId: 2468,
                areaName: '文昌市',
                parentId: 104,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '琼海市',
              record: {
                areaId: 2466,
                areaName: '琼海市',
                parentId: 104,
                areaType: 2
              },
              leaf: true
            },
            {
              text: '五指山市',
              record: {
                areaId: 2465,
                areaName: '五指山市',
                parentId: 104,
                areaType: 2
              },
              leaf: true
            }
          ]
        }
      ]
    }
  }
});