/*
 * File: app/store/optSkill.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.store.optSkill', {
  extend: 'Ext.data.Store',

  requires: [
    'ZJ02.model.optSkill'
  ],

  config: {
    data: [
      {
        functionId: 66,
        functionName: '计算机/互联网/通信/电子',
        functionType: 1,
        parentId: 0
      },
      {
        functionId: 66,
        functionName: '计算机/互联网/通信/电子',
        functionType: 1,
        parentId: 0
      }
    ],
    model: 'ZJ02.model.optSkill',
    storeId: 'optSkill'
  }
});