/*
 * File: app/store/optSchool.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.store.optSchool', {
  extend: 'Ext.data.Store',

  requires: [
    'ZJ02.model.optSchool'
  ],

  config: {
    data: [
      {
        schoolId: 1,
        schoolname: '上海交通大学',
        num: 1000,
        iconImage: '/backend/20131223/default/5.png',
        shortPinyin: '2014/1/23 16:49:12',
        longPinyin: 'java软件工程师',
        currentNum: 1,
        address: '上海创驰网络有限公司',
        zipCode: '70',
        phone: 784,
        email: 123,
        website: '70',
        intro: 1,
        busScope: '2014/1/23 16:49:12',
        details: 1,
        provinceId: '2014/1/23 16:49:12',
        districtId: 1
      },
      {
        schoolId: 2,
        schoolname: '上海农业大学',
        num: 1000,
        iconImage: '/backend/20131223/default/5.png',
        shortPinyin: '2014/1/23 16:49:12',
        longPinyin: 'java软件工程师',
        currentNum: 1,
        address: '上海创驰网络有限公司',
        zipCode: '70',
        phone: 784,
        email: 123,
        website: '70',
        intro: 1,
        busScope: '2014/1/23 16:49:12',
        details: 1,
        provinceId: '2014/1/23 16:49:12',
        districtId: 1
      }
    ],
    model: 'ZJ02.model.optSchool',
    storeId: 'optSchool'
  }
});