/*
 * File: app/store/recruitment.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.store.recruitment', {
  extend: 'Ext.data.Store',

  requires: [
    'ZJ02.model.recruitment'
  ],

  config: {
    data: [
      {
        recruitmentId: 1,
        recruitmentTitle: '腾讯公司宣讲会',
        place: '复旦大学文学楼202会议室01-08',
        beginTime: '2014/2/2'
      },
      {
        recruitmentId: 2,
        recruitmentTitle: '腾讯公司宣讲会',
        place: '复旦大学文学楼202会议室01-08',
        beginTime: '2014/2/2'
      }
    ],
    model: 'ZJ02.model.recruitment',
    storeId: 'recruitment'
  }
});