/*
 * File: app/store/Subscription.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.store.Subscription', {
  extend: 'Ext.data.Store',

  requires: [
    'ZJ02.model.Subscription'
  ],

  config: {
    data: [
      {
        subscriptionId: 1,
        searchName: '上海+产品经理',
        todayPositionCount: 2,
        positionCount: 99
      },
      {
        subscriptionId: 1,
        searchName: '上海+产品经理',
        todayPositionCount: 2,
        positionCount: 99
      },
      {
        subscriptionId: 1,
        searchName: '上海+产品经理',
        todayPositionCount: 2,
        positionCount: 99
      },
      {
        subscriptionId: 1,
        searchName: '上海+产品经理',
        todayPositionCount: 2,
        positionCount: 99
      },
      {
        subscriptionId: 1,
        searchName: '上海+产品经理',
        todayPositionCount: 2,
        positionCount: 99
      }
    ],
    model: 'ZJ02.model.Subscription',
    storeId: 'Subscription'
  }
});