/*
 * File: app/store/TopicReply.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.store.TopicReply', {
  extend: 'Ext.data.Store',

  requires: [
    'ZJ02.model.TopicReply'
  ],

  config: {
    data: [
      {
        id: 1,
        title: '我的3个月求职历程经验分享',
        date: '2013-01-01',
        cc_zan: 10,
        cc_comment: 100,
        badge: 18
      },
      {
        id: 2,
        title: '我的3个月求职历程经验分享',
        date: '2013-01-01',
        cc_zan: 10,
        cc_comment: 100,
        badge: 18
      },
      {
        id: 3,
        title: '我的3个月求职历程经验分享',
        date: '2013-01-01',
        cc_zan: 10,
        cc_comment: 100,
        badge: 18
      },
      {
        id: 4,
        title: '我的3个月求职历程经验分享',
        date: '2013-01-01',
        cc_zan: 10,
        cc_comment: 100,
        badge: 18
      },
      {
        id: 5,
        title: '我的3个月求职历程经验分享',
        date: '2013-01-01',
        cc_zan: 10,
        cc_comment: 100,
        badge: 18
      }
    ],
    model: 'ZJ02.model.TopicReply',
    storeId: 'TopicReply'
  }
});