/*
 * File: app/store/UserCenterNav.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.store.UserCenterNav', {
  extend: 'Ext.data.Store',

  requires: [
    'ZJ02.model.UserCenterNav'
  ],

  config: {
    data: [
      {
        title: '申请记录',
        badge: '',
        action: 'apply_log'
      },
      {
        title: '职位收藏',
        badge: '',
        action: 'job_favourite'
      },
      {
        title: '谁看过我',
        badge: '',
        action: 'who_see_me'
      }/*, {title: '我的发布',
      badge: '20',
      action: 'my_publish'
    },
    {
      title: '文章收藏',
      badge: '20',
      action: 'article_favourite'
    }*/],
    model: 'ZJ02.model.UserCenterNav',
    storeId: 'UserCenterNav'
  }
});