/*
 * File: app/view/AccountBindSinaWeibo.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.view.AccountBindSinaWeibo', {
  extend: 'Ext.Container',

  requires: [
    'Ext.TitleBar',
    'Ext.Button',
    'Ext.Panel'
  ],

  config: {
    layout: 'fit',
    items: [
      {
        xtype: 'titlebar',
        cls: 'zjs-bg-green',
        docked: 'top',
        ui: 'zjs',
        title: '新浪微博账号绑定',
        items: [
          {
            xtype: 'button',
            height: 30,
            itemId: 'mybutton23',
            ui: 'plain',
            width: 30,
            icon: '',
            iconCls: 'zjs-icon-back',
            text: 'back'
          }
        ]
      },
      {
        xtype: 'panel',
        hidden: false,
        itemId: 'iframe_con'
      }
    ],
    listeners: [
      {
        fn: 'onMybutton23Tap1',
        event: 'tap',
        delegate: '#mybutton23'
      }
    ]
  },

  onMybutton23Tap1: function(button, e, eOpts) {
    pop_view();
  },

  old_init: function() {
    this.callParent();

    var _this = this;

    var platform = 'sina';
    var iframe_src = build_api('bind_'+platform);
    var x$toggle = x$('toggle_ab_'+platform);
    var token = get_s('token');
    iframe_src = iframe_src+'?token='+token+'&flag=mobile';


    var init_iframe = function( $iframe ){
      //console.log(iframe_src);
      //console.log($iframe.get(0).src);
      $iframe.attr('src',iframe_src);

      heart_beat_check(function(code,status){

        switch(code){
          case 0:
            toast('恭喜你，绑定成功！');
            _this.up('navigationview').pop();
            break;
          case 1:
            toast('操作超时，请重试。');
            x$toggle.setValue(0);
            _this.up('navigationview').pop();
            break;
          case 2:
            toast('您的网络似乎有问题，请确认网络连接正常后再试。');
            x$toggle.setValue(0);
            _this.up('navigationview').pop();
            break;
          case 3:
            toast('服务器访问错误，请稍候再试。');
            x$toggle.setValue(0);
            _this.up('navigationview').pop();
            break;
        }


        console.log(status);
      });

    };




    var heart_beat_check = function(callback){
      var timeout = 600;
      var beat_timeout = 30;
      var beat_try = 10;
      var start_time = (new Date()).getTime();
      var is_free = true;
      var interval_handler;

      var err_da = ['SUCCESS','TIMEOUT','NET_TRYOUT','API_ERROR'];


      var tick_beat = function(){

        console.log('beat_try ' + beat_try);
        console.log('timeout ' + timeout);


        if( timeout <= 0 ){
          clearInterval(interval_handler);
          callback(1,err_da);
          return;
        }

        if( beat_try <= 0 ){
          clearInterval(interval_handler);
          callback(2,err_da);
          return;
        }

        is_free = false;

        send_request( {
          api:'check_bind',
          method:'POST',
          params:{
            platform:platform
          },
          success:function(result, request){
            is_free = true;
            if( result.code == '0000' ){
              if( result.result ){
                clearInterval(interval_handler);
                callback(0,err_da);
                return;
              }
            }else{
              clearInterval(interval_handler);
              callback(3,err_da);
              return;
            }
          },
          fail:function(result){
            is_free = true;
            beat_try --;
          },
          text:'加载中',
          silent:true,
          trigger:_this,
          check_login:false
        } );


      };


      window.bind_check_beat_handler_sina = interval_handler = window.setInterval(function(){
        if(is_free){
          tick_beat();
        }
        timeout--;
      },1000);



    };







    Ext.Viewport.setMasked({
      xtype: 'loadmask',
      message: '加载中，请稍候。',
      transparent:true
    });

    var iframe_seek_handler = window.setInterval(function(){
      var $iframe = jQuery('#if_sinaweibo');
      if( $iframe && $iframe.length ){
        clearInterval(iframe_seek_handler);
        Ext.Viewport.unmask();
        init_iframe($iframe);
      }
    },1000);




  },

  update: function(_p) {
    var _this = this;


    _this.f_pop_refresh = true;


    var platform = 'sina';
    var flag = 'mobile';
    var return_url = 'http://popview';//get_return_url(platform);
    var token = get_s('token');


    var x$iframe_con = i$('iframe_con',_this);
    var $iframe_con = j$(x$iframe_con);
    var con_id = x$iframe_con.getId();


    var $iframe_con_html = $iframe_con.find('.x-inner');

    var url = build_api('bind_iframe_sina');
    url = url + '/?platform='+platform+'&flag='+flag+'&return_url='+return_url+'&token='+token;

    //var $iframe = jQuery('<iframe src="about:blank" scrolling="no" allowtransparency="true" frameborder="0" width="100%" height="1000" name="'+con_id+'_iframe" id="'+con_id+'_iframe"></iframe>');

    //$iframe_con_html.append($iframe);

    //var ref = window.open('bind_loading.html?url='+encodeURIComponent(url), '_blank' ,'location=no');
    var ref = window.open(url, '_blank' ,'location=no');

    ref.addEventListener('loadstart', function(event) {
      //alert(event.url);
      if( event.url == 'popview' || event.url == 'http://popview' || event.url == 'http://popview/'  || event.url == 'http://www.popview/'  || event.url == 'www.popview/' || event.url == 'www.popview' ){
        ref.close();
      }
    });

    ref.addEventListener('exit', function(event) {
      pop_view(true);
    });


    /*

    window.plugins.ChildBrowser.showWebPage(url,{
      showLocationBar:false,
      showAddress:false,
      showNavigationBar:false
    });


    window.plugins.ChildBrowser.onClose = function () {
      //alert('childBrowser has closed');
      pop_view(true);
    };

    window.plugins.ChildBrowser.onLocationChange = function (url) {
      if(url == 'about:blank'){
        window.plugins.ChildBrowser.close();
      }
      //alert('childBrowser has loaded ' + url);
    };

    */


    /*

    var ref = window.open(url, con_id+'_iframe');

    ref.addEventListener('loadstart', function() { alert('LOAD START '+event.url); });
    ref.addEventListener('loadstop', function() { alert('LOAD STOP'); });
    ref.addEventListener('loaderror', function() { alert('LOAD ERROR'); });
    ref.addEventListener('exit', function() { alert('EXIT'); });

    */


  }

});