/*
 * File: app/view/AcSubmit.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.view.AcSubmit', {
  extend: 'Ext.Container',

  requires: [
    'Ext.TitleBar',
    'Ext.Button',
    'Ext.form.Panel',
    'Ext.field.TextArea'
  ],

  config: {
    cls: 'zjs',
    layout: 'card',
    items: [
      {
        xtype: 'titlebar',
        cls: 'zjs-bg-green',
        docked: 'top',
        ui: 'zjs',
        title: '发布',
        items: [
          {
            xtype: 'button',
            height: 30,
            itemId: 'mybutton23',
            ui: 'plain',
            width: 30,
            icon: '',
            iconCls: 'zjs-icon-back',
            text: 'back'
          },
          {
            xtype: 'button',
            align: 'right',
            itemId: 'mybutton44',
            text: '提交'
          }
        ]
      },
      {
        xtype: 'formpanel',
        scrollable: 'vertical',
        items: [
          {
            xtype: 'textareafield',
            height: 150,
            placeHolder: '  求职路上，你有什么经验与大家分享分享……'
          }
        ]
      }
    ],
    listeners: [
      {
        fn: 'onMybutton23Tap',
        event: 'tap',
        delegate: '#mybutton23'
      },
      {
        fn: 'onMybutton44Tap',
        event: 'tap',
        delegate: '#mybutton44'
      }
    ]
  },

  onMybutton23Tap: function(button, e, eOpts) {
    button.up('navigationview').pop();
  },

  onMybutton44Tap: function(button, e, eOpts) {
    Ext.Msg.alert("您的文章已提交，感谢您的支持！");
    button.up('navigationview').pop();
  }

});