/*
 * File: app/view/AppConfig.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.view.AppConfig', {
  extend: 'Ext.Container',

  requires: [
    'Ext.TitleBar',
    'Ext.Button',
    'Ext.form.Panel',
    'Ext.form.FieldSet',
    'Ext.field.TextArea'
  ],

  config: {
    layout: 'fit',
    items: [
      {
        xtype: 'titlebar',
        cls: 'zjs-bg-green',
        docked: 'top',
        ui: 'zjs',
        title: 'App Config',
        items: [
          {
            xtype: 'button',
            height: 30,
            itemId: 'mybutton23',
            ui: 'plain',
            width: 30,
            icon: '',
            iconCls: 'zjs-icon-back',
            text: 'back'
          },
          {
            xtype: 'button',
            align: 'right',
            itemId: 'mybutton45',
            text: '提交'
          }
        ]
      },
      {
        xtype: 'formpanel',
        items: [
          {
            xtype: 'fieldset',
            title: 'Path Config',
            items: [
              {
                xtype: 'textareafield',
                id: 'app-config-api-root',
                label: 'API Root'
              }
            ]
          },
          {
            xtype: 'fieldset',
            title: 'Default Variables',
            items: [
              {
                xtype: 'textfield',
                id: 'app-config-city-id',
                label: 'cityId'
              }
            ]
          }
        ]
      }
    ],
    listeners: [
      {
        fn: 'onMybutton23Tap',
        event: 'tap',
        delegate: '#mybutton23'
      },
      {
        fn: 'onMybutton44Tap1',
        event: 'tap',
        delegate: '#mybutton45'
      }
    ]
  },

  onMybutton23Tap: function(button, e, eOpts) {
    button.up('navigationview').pop();
  },

  onMybutton44Tap1: function(button, e, eOpts) {
    var x$api_root = x$('app-config-api-root');
    var x$cityId = x$('app-config-city-id');

    var api_root = x$api_root.getValue();
    var cityId = x$cityId.getValue();

    if( api_root ){
      set_s('_AJAX_ROOT',api_root);
      _G._AJAX_ROOT = api_root;
    }

    if( cityId ){
      set_s('_cityId',cityId);
      _G._cityId = cityId;
    }

    toast("设置成功！");
    button.up('navigationview').pop();
  },

  update: function(_p) {

    var api_root = get_s('_AJAX_ROOT') || _G._AJAX_ROOT;
    var cityId = get_s('_cityId') || _G._cityId;


    var x$api_root = x$('app-config-api-root');
    var x$cityId = x$('app-config-city-id');


    x$api_root.setValue(api_root);
    x$cityId.setValue(cityId);


  },

  initialize: function() {
    this.callParent();


    this.update();
  }

});