/*
 * File: app/view/CampusTalkDetail.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.view.CampusTalkDetail', {
  extend: 'Ext.Container',

  requires: [
    'Ext.TitleBar',
    'Ext.Button',
    'Ext.Panel',
    'Ext.Label',
    'Ext.dataview.List',
    'Ext.XTemplate'
  ],

  config: {
    cls: 'zjs',
    layout: 'card',
    data: [
      {
        text: '1小时前提醒',
        value: ''
      }
    ],
    items: [
      {
        xtype: 'titlebar',
        cls: 'zjs-bg-green',
        docked: 'top',
        ui: 'zjs',
        title: '  宣讲会详情',
        items: [
          {
            xtype: 'button',
            height: 30,
            id: 'campus_detail_back',
            itemId: 'campus_detail_back',
            ui: 'plain',
            width: 30,
            icon: '',
            iconCls: 'zjs-icon-back',
            text: 'back'
          },
          {
            xtype: 'button',
            align: 'right',
            height: 30,
            id: 'campus_detail_share',
            itemId: 'campus_detail_share',
            ui: 'plain',
            width: 30,
            icon: '',
            iconCls: 'zjs-icon-share',
            text: 'back'
          }
        ]
      },
      {
        xtype: 'panel',
        itemId: 'c_t_d_scp',
        scrollable: 'vertical',
        items: [
          {
            xtype: 'label',
            cls: 'article-headline',
            html: '载入中，请稍候...',
            itemId: 'campus_detail_title',
            padding: '0.5em',
            style: 'text-align:center;font-size:20px;'
          },
          {
            xtype: 'panel',
            cls: 'detail_panel',
            padding: '0.2em 0.5em 0.2em 0.8em',
            layout: 'hbox',
            items: [
              {
                xtype: 'panel',
                flex: 1,
                cls: 'col-content',
                itemId: 'campus_detail_info',
                padding: '0 1em 0 0'
              },
              {
                xtype: 'panel',
                cls: 'col-button',
                height: 40,
                width: 40,
                items: [
                  {
                    xtype: 'button',
                    cls: 'x-ns-alarm',
                    itemId: 'mybutton42'
                  }
                ]
              }
            ]
          },
          {
            xtype: 'panel',
            cls: 'detail_content',
            itemId: 'campus_detail_desc',
            padding: '1em'
          }
        ]
      },
      {
        xtype: 'container',
        centered: true,
        cls: 'campus_pop_share_sns',
        height: 130,
        hidden: true,
        html: '<div class="sns_share_list"> <a href="javascript:;" class="btn_sina"><i></i>   <p>新浪微博</p>   </a> <!--<a href="javascript:;" class="btn_qq"><i></i>   <p>腾讯微博</p>   </a> <a href="javascript:;" class="btn_renren"><i></i>   <p>人人网</p>   </a>--> </div>',
        itemId: 'campus_pop_share_sns',
        width: 100,
        hideOnMaskTap: true,
        modal: true
      },
      {
        xtype: 'container',
        centered: true,
        height: 200,
        hidden: true,
        itemId: 'cnl_pop_alerttime',
        width: 280,
        layout: 'fit',
        modal: true,
        items: [
          {
            xtype: 'titlebar',
            docked: 'top',
            title: '推送时间',
            items: [
              {
                xtype: 'button',
                itemId: 'cnl_btn_back',
                text: '返回'
              }
            ]
          },
          {
            xtype: 'list',
            itemId: 'cnl_alerttime',
            disableSelection: true,
            itemCls: 'leaf_list',
            itemTpl: [
              '<div class="{__leaf_cls}">{text}</div>'
            ]
          }
        ]
      }
    ],
    listeners: [
      {
        fn: 'onCampus_detail_backTap',
        event: 'tap',
        delegate: '#campus_detail_back'
      },
      {
        fn: 'onCampus_detail_shareTap',
        event: 'tap',
        delegate: '#campus_detail_share'
      },
      {
        fn: 'onMybutton42Tap',
        event: 'tap',
        delegate: '#mybutton42'
      },
      {
        fn: 'onMybutton23Tap311111112',
        event: 'tap',
        delegate: '#cnl_btn_back'
      }
    ]
  },

  onCampus_detail_backTap: function(button, e, eOpts) {
    button.up('navigationview').pop();
  },

  onCampus_detail_shareTap: function(button, e, eOpts) {
    var _this = this;

    var x$pop = _this.down('#campus_pop_share_sns');

    var $pop = j$(x$pop);


    x$pop.show();
  },

  onMybutton42Tap: function(button, e, eOpts) {
    var _this = this;

    _this.down('#cnl_pop_alerttime').show();
  },

  onMybutton23Tap311111112: function(button, e, eOpts) {
    var _this = this;

    if( !_this.CNL_pushtime.pop() ){
      window.setTimeout(function(){
        _this.down('#cnl_pop_alerttime').hide();
      },320);
    }

  },

  update: function(_p) {

    var _this = this;



    var x$title = _this.down('#campus_detail_title');
    var x$info = _this.down('#campus_detail_info');
    var x$desc = _this.down('#campus_detail_desc');


    if( _p && _p.id ){

      send_request( {
        api:'recruit_detail',
        method:'POST',
        params:{
          recruitmentId:_p.id
        },
        success:function(result, request){
          if( result.success ){
            switch( result.code ){
              case '0000':
                //成功
                //console.log(result);

                if( result.data ){

                  var info_html = '<p>时间：'+(result.data.beginTime||'暂无')+'</p> <p>城市：'+(result.data.cityName||'暂无')+'</p> <p>学校：'+(result.data.schoolName||'暂无')+'</p> <p>地点：'+(result.data.place||'暂无')+'</p>';

                  x$title.setHtml(result.data.recruitmentTitle);
                  x$info.setHtml(info_html);
                  x$desc.setHtml(result.data.recruitmentDescription);

                  _this.result_data = result.data;

                  refresh_scroll(_this.down('#c_t_d_scp'));

                }else{
                  x$title.setHtml('无数据');
                }


                break;
              case '1001':
                //失败
                break;
              default:
                toast("errCode:"+result.code);
                break;
            }
          }else{

          }
        },
        fail:function(result){
          toast("您的网络似乎有点问题，请稍候再试！");
        },
        text:'加载中',
        silent:false,
        trigger:_this,
        check_login:true
      } );

    }





    var reminde_options = [
      {
        text:'提前30分钟',
        value:30
      },
      {
        text:'提前1小时',
        value:60
      },
      {
        text:'提前2小时',
        value:120
      },
      {
        text:'提前5小时',
        value:300
      },
      {
        text:'提前12小时',
        value:720
      },
      {
        text:'提前24小时',
        value:1440
      }
    ];



    var x$pop =  _this.down('#cnl_pop_alerttime');
    var x$list = _this.down('#cnl_alerttime');

    _this.CNL_pushtime = new LD_Nested_List( x$list,reminde_options,'items',function(data){
      var newValue = data.value;

      window.setTimeout(function(){
        x$pop.hide();
      },320);

      if(newValue > 0){

        var start_time = parse_date(_this.result_data.beginTime).dateobj;

        var remind_time = new Date(start_time - newValue*60000);

        var remind_date = parse_date(remind_time);

        var remind_date_str = remind_date.fullyeardatetime;

        //alert(_this.result_data.recruitmentId);
        //alert(remind_date_str);
        //alert(newValue);

        send_request( {
          api:'recruit_remind_add',
          method:'POST',
          params:{
            recruitmentId:_this.result_data.recruitmentId,
            remindTime:remind_date_str,
            aheadOfTime:newValue
          },
          success:function(result, request){

            //alert(result.success);
            //alert(result.code);

            if( result.success ){
              switch( result.code ){
                case '0000':
                  //成功
                  //console.log(result);
                  toast('添加提醒成功！');
                  break;
                case '1001':
                  //失败
                  break;
                default:
                  toast("errCode:"+result.code);
                  break;
              }
            }else{
              toast("添加失败，请稍候再试。");
            }
          },
          fail:function(result){

            alert(result);

            toast("您的网络似乎有点问题，请稍候再试！");
          },
          text:'加载中',
          silent:false,
          trigger:_this,
          check_login:true
        } );

      }

    } );






  },

  initialize: function() {
    this.callParent();

    var _this = this;

    var x$pop_sns = _this.down('#campus_pop_share_sns');

    x$pop_sns.on('show',function(){

      var _pop = this;

      var x$pop = _this.down('#campus_pop_share_sns');


      var $pop = j$(x$pop);

      var $btn_sina = $pop.find('.btn_sina');
      var $btn_qq = $pop.find('.btn_qq');
      var $btn_renren = $pop.find('.btn_renren');



      $btn_sina.unbind('click').click(function(){

        x$pop.hide();

        get_access_token(function( result,success ){
          if(success){
            if( result && result.sina){
              //x$pop.hide();
              change_page('ShareFormSina',_this,{sns:result.sina,data:_this.result_data});
            }else{
              toast('您尚未绑定新浪微博账号，请先到“更多”中绑定新浪微博账号。');
            }
          }else{
            toast('获取账号绑定信息失败，请检查网络或稍候再试。');
          }
        },'sina');
      });




      $btn_qq.unbind('click').click(function(){

        x$pop.hide();

        get_access_token(function( result,success ){
          if(success){
            if( result && result.qq ){
              //x$pop.hide();
              change_page('ShareFormQQ',_this,{sns:result.sina,data:_this.result_data});
            }else{
              toast('您尚未绑定腾讯微博账号，请先到“更多”中绑定腾讯微博账号。');
            }
          }else{
            toast('获取账号绑定信息失败，请检查网络或稍候再试。');
          }
        },'qq');
      });




      $btn_renren.unbind('click').click(function(){

        x$pop.hide();

        get_access_token(function( result,success ){
          if(success){
            if( result && result.renren ){
              //x$pop.hide();
              change_page('ShareFormRenren',_this,{sns:result.sina,data:_this.result_data});
            }else{
              toast('您尚未绑定人人网账号，请先到“更多”中绑定人人网账号。');
            }
          }else{
            toast('获取账号绑定信息失败，请检查网络或稍候再试。');
          }
        },'renren');
      });




    });
  }

});