/*
 * File: app/view/CityChooser_CNL.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.view.CityChooser_CNL', {
  extend: 'Ext.Container',

  requires: [
    'Ext.TitleBar',
    'Ext.Button',
    'Ext.dataview.List',
    'Ext.XTemplate'
  ],

  config: {
    layout: 'fit',
    items: [
      {
        xtype: 'titlebar',
        cls: 'zjs-bg-green',
        docked: 'top',
        ui: 'zjs',
        title: '选择城市',
        items: [
          {
            xtype: 'button',
            height: 30,
            itemId: 'mybutton23',
            ui: 'plain',
            width: 30,
            icon: '',
            iconCls: 'zjs-icon-back',
            text: 'back'
          }
        ]
      },
      {
        xtype: 'list',
        itemId: 'city_list',
        disableSelection: true,
        itemCls: 'leaf_list',
        itemTpl: [
          '<div class="{__leaf_cls}">{text}</div>'
        ]
      }
    ],
    listeners: [
      {
        fn: 'onMybutton23Tap31',
        event: 'tap',
        delegate: '#mybutton23'
      }
    ]
  },

  onMybutton23Tap31: function(button, e, eOpts) {
    var _this = this;

    if( !_this.CityNestedList.pop() ){
      _this.up('navigationview').pop();
    }

  },

  update: function(_p) {
    var _this = this;

    var x$list = _this.down('#city_list');

    _this.CityNestedList = new LD_Nested_List( x$list,_DATA_CITYS.items,'items',function(data){

      change_city(data.record.areaId,data.record.areaName);
      _this.up('navigationview').pop();

    } );



  }

});