/*
 * File: app/view/CompanyNear.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.view.CompanyNear', {
  extend: 'Ext.Container',

  requires: [
    'Ext.TitleBar',
    'Ext.Button',
    'Ext.SegmentedButton',
    'Ext.Panel',
    'Ext.XTemplate',
    'Ext.dataview.List'
  ],

  config: {
    layout: 'fit',
    items: [
      {
        xtype: 'titlebar',
        cls: 'zjs-bg-green',
        docked: 'top',
        ui: 'zjs',
        title: '附近企业',
        items: [
          {
            xtype: 'button',
            height: 30,
            itemId: 'mybutton23',
            ui: 'plain',
            width: 30,
            icon: '',
            iconCls: 'zjs-icon-back',
            text: 'back'
          },
          {
            xtype: 'button',
            align: 'right',
            itemId: 'mybutton60',
            ui: 'plain',
            iconCls: 'zjs-icon-mark'
          }
        ]
      },
      {
        xtype: 'segmentedbutton',
        cls: 'zjs-filter-menu',
        docked: 'top',
        height: 40,
        itemId: 'mysegmentedbutton',
        defaults: {
          flex: 1
        },
        items: [
          {
            xtype: 'button',
            id: 'cnear_btn_industry',
            itemId: 'mybutton1',
            text: '选择行业'
          },
          {
            xtype: 'button',
            id: 'cnear_btn_type',
            itemId: 'mybutton2',
            text: '企业性质'
          },
          {
            xtype: 'button',
            hidden: true,
            id: 'cnear_btn_school',
            itemId: 'mybutton4',
            text: '选择学校'
          }
        ]
      },
      {
        xtype: 'panel',
        hidden: false,
        layout: 'fit',
        items: [
          {
            xtype: 'dataview',
            cls: 'zjs-listview-icon',
            id: 'list_cnear',
            itemId: 'mydataview4',
            minHeight: 180,
            scrollable: 'vertical',
            disableSelection: true,
            itemTpl: [
              '<div class="li">',
              '	<div class="icon">',
              '    <span><img src="{companyLogo}"/></span>',
              '  </div>',
              '  <div class="c">',
              '  	<h4>{companyName}</h4>',
              '    <p>企业简介：{profile}</p>',
              '  </div>',
              '  <div class="i">',
              '  	<span></span>',
              '  </div>',
              '</div>'
            ]
          }
        ]
      },
      {
        xtype: 'panel',
        cls: 'zjs-dd-filter-ms',
        height: 300,
        hidden: true,
        id: 'cnear_fo_industry',
        layout: 'hbox',
        items: [
          {
            xtype: 'panel',
            flex: 4,
            cls: 'col-1',
            layout: 'fit',
            scrollable: 'vertical',
            items: [
              {
                xtype: 'list',
                id: 'cnear_filter_list_industry_lv1',
                itemId: 'cnear_filter_list_industry_lv1',
                itemTpl: [
                  '<div>{industryName}',
                  '  <tpl if="has_child &gt; 0">',
                  '    <div class="more_arr">&gt;</div>',
                  '  </tpl>',
                  '</div>'
                ]
              }
            ]
          },
          {
            xtype: 'panel',
            flex: 6,
            cls: 'col-2',
            layout: 'fit',
            scrollable: 'vertical',
            items: [
              {
                xtype: 'list',
                id: 'cnear_filter_list_industry_lv2',
                itemId: 'cnear_filter_list_industry_lv2',
                itemTpl: [
                  '<div>{industryName}</div>'
                ],
                itemHeight: 30
              }
            ]
          }
        ]
      },
      {
        xtype: 'panel',
        cls: 'zjs-dd-filter-ss',
        height: 300,
        hidden: true,
        id: 'cnear_fo_type',
        layout: 'hbox',
        items: [
          {
            xtype: 'panel',
            flex: 1,
            cls: 'col-1',
            layout: 'fit',
            scrollable: 'vertical',
            items: [
              {
                xtype: 'list',
                id: 'cnear_filter_list_type',
                itemId: 'mylist',
                itemTpl: [
                  '<div>{name}</div>'
                ],
                itemHeight: 30
              }
            ]
          }
        ]
      },
      {
        xtype: 'panel',
        cls: 'zjs-dd-filter-ss',
        height: 300,
        hidden: true,
        id: 'cnear_fo_school',
        layout: 'hbox',
        items: [
          {
            xtype: 'panel',
            flex: 1,
            cls: 'col-1',
            layout: 'fit',
            scrollable: 'vertical',
            items: [
              {
                xtype: 'list',
                id: 'cnear_filter_list_school',
                itemId: 'mylist',
                itemTpl: [
                  '<div>{schoolname}</div>'
                ],
                itemHeight: 30
              }
            ]
          }
        ]
      }
    ],
    listeners: [
      {
        fn: 'onMybutton23Tap3',
        event: 'tap',
        delegate: '#mybutton23'
      },
      {
        fn: 'onMybutton60Tap',
        event: 'tap',
        delegate: '#mybutton60'
      },
      {
        fn: 'onMybutton1Tap',
        event: 'tap',
        delegate: '#cnear_btn_industry'
      },
      {
        fn: 'onMybutton2Tap',
        event: 'tap',
        delegate: '#cnear_btn_type'
      },
      {
        fn: 'onMybutton2Tap11',
        event: 'tap',
        delegate: '#cnear_btn_school'
      },
      {
        fn: 'onMydataview2ItemTap11',
        event: 'itemtap',
        delegate: '#list_cnear'
      },
      {
        fn: 'onCampustalk_filter_list_industry_lv1ItemTap',
        event: 'itemtap',
        delegate: '#cnear_filter_list_industry_lv1'
      },
      {
        fn: 'onCampustalk_filter_list_industry_lv2ItemTap',
        event: 'itemtap',
        delegate: '#cnear_filter_list_industry_lv2'
      },
      {
        fn: 'onCampustalk_filter_list_schoolItemTap1',
        event: 'itemtap',
        delegate: '#cnear_filter_list_type'
      },
      {
        fn: 'onCampustalk_filter_list_schoolItemTap',
        event: 'itemtap',
        delegate: '#cnear_filter_list_school'
      }
    ]
  },

  onMybutton23Tap3: function(button, e, eOpts) {
    button.up('navigationview').pop();
  },

  onMybutton60Tap: function(button, e, eOpts) {

    var x$industry = x$('cnear_fo_industry');
    var x$type = x$('cnear_fo_type');
    var x$school = x$('cnear_fo_school');


    var params = {
      pageSize:100,
      location:'{"lat":'+window.lat+',"lng":'+window.lng+'}',
      distance:1000
    };

    var cur_industry_val = get_data( 'cnear_fo_industry','value' );
    if(cur_industry_val){
      params.industryId = cur_industry_val;
    }

    var cur_type_val = get_data( 'cnear_fo_type','value' );
    if(cur_type_val){
      params.companyType = cur_type_val;
    }

    var cur_school_val = get_data( 'cnear_fo_school','value' );
    if(cur_school_val){
      params.schoolId = cur_school_val;
    }


    change_page('CompanyMap',button,params);
  },

  onMybutton1Tap: function(button, e, eOpts) {
    var x$flyout = x$('cnear_fo_industry');
    var init_fo_func = this.init_fo_industry;

    if( is_active(button) ){
      this.reset_fo();
    }else{
      this.reset_fo();
      x$flyout.show();
      set_active(button);
      init_fo_func.apply(this,[]);
    }
  },

  onMybutton2Tap: function(button, e, eOpts) {
    var x$flyout = x$('cnear_fo_type');
    var init_fo_func = this.init_fo_type;

    if( is_active(button) ){
      this.reset_fo();
    }else{
      this.reset_fo();
      x$flyout.show();
      set_active(button);
      init_fo_func.apply(this,[]);
    }

  },

  onMybutton2Tap11: function(button, e, eOpts) {
    var x$flyout = x$('cnear_fo_school');
    var init_fo_func = this.init_fo_school;

    if( is_active(button) ){
      this.reset_fo();
    }else{
      this.reset_fo();
      x$flyout.show();
      set_active(button);
      init_fo_func.apply(this,[]);
    }

  },

  onMydataview2ItemTap11: function(dataview, index, target, record, e, eOpts) {
    var item_data = record.data;
    change_page('CompanyDetail',dataview,item_data);
  },

  onCampustalk_filter_list_industry_lv1ItemTap: function(dataview, index, target, record, e, eOpts) {
    var x$list_lv2 = x$('cnear_filter_list_industry_lv2');

    var data = record.data;

    if(data.has_child){
      set_store_data(x$list_lv2,data.childs);
    }else{
      set_store_data(x$list_lv2,[]);
      this.set_industry(data.industryId,data.industryName);
    }

  },

  onCampustalk_filter_list_industry_lv2ItemTap: function(dataview, index, target, record, e, eOpts) {
    var data = record.data;
    this.set_industry(data.industryId,data.industryName);

  },

  onCampustalk_filter_list_schoolItemTap1: function(dataview, index, target, record, e, eOpts) {
    var data = record.data;
    this.set_type(data.value,data.name);
  },

  onCampustalk_filter_list_schoolItemTap: function(dataview, index, target, record, e, eOpts) {
    var data = record.data;
    this.set_school(data.schoolId,data.schoolname);
  },

  initialize: function() {
    this.callParent();

  },

  update: function(_p) {
    var _this = this;


    var x$industry = x$('cnear_fo_industry');
    var x$type = x$('cnear_fo_type');
    var x$school = x$('cnear_fo_school');



    var request_data = function(){

      var params = {
        pageSize:100,
        location:JSON.stringify(fix_location(get_location())),
        distance:1000
      };

      var cur_industry_val = get_data( 'cnear_fo_industry','value' );
      if(cur_industry_val){
        params.industryId = cur_industry_val;
      }

      var cur_type_val = get_data( 'cnear_fo_type','value' );
      if(cur_type_val){
        params.companyType = cur_type_val;
      }

      var cur_school_val = get_data( 'cnear_fo_school','value' );
      if(cur_school_val){
        params.schoolId = cur_school_val;
      }


      console.log(params);

      send_request( {
        api:'c_near',
        method:'POST',
        params:params,
        success:function(result, request){
          if( result.success ){
            switch( result.code ){
              case '0000':
                //成功
                console.log(result);
                _this.build_list(result.data);
                break;
              case '1001':
                //失败
                break;
              default:
                toast("errCode:"+result.code);
                break;
            }
          }else{

          }
        },
        fail:function(result){
          toast("您的网络似乎有点问题，请稍候再试！");
        },
        text:'加载中',
        silent:false,
        trigger:_this,
        check_login:true
      } );


    };



    if( need_geo_update() ){
      update_location(function(loc,status,e){

        if(loc){
          request_data();
        }else{
          toast('抱歉，无法获取您的当前位置。');
          //toast(e.message);
          x$type.up('navigationview').pop();
        }

      },{
        silent:false
      });

    }else{
      request_data();
    }




  },

  build_list: function(data) {
    var x$list = x$('list_cnear');

    /*
    for( var i=0;i<data.length;i++ ){
      var date_ra = parse_date(data[i].refreshiTime,'date_');
      jQuery.extend( data[i],date_ra );
    }
    */

    if(data.length){
      x$list.removeCls('zj-list-no-data');
      set_store_data( x$list,data );
    }else{
      x$list.addCls('zj-list-no-data');
      set_store_data( x$list,[] );
    }


    refresh_scroll(x$list);
  },

  init_fo_industry: function() {
    var x$flyout = x$('cnear_fo_industry');

    var x$list_lv1 = x$('cnear_filter_list_industry_lv1');
    var x$list_lv2 = x$('cnear_filter_list_industry_lv2');


    var key_id = 'industryId';
    var key_parent = 'parentId';



    var _this = this;

    var init_fo = function(data){
      console.log(data);

      var da_lv1 = [
        {
          has_child:0,
          industryId:0,
          industryName:'重置',
          is_reset:true
        }
      ];
      var da_lv2 = {};

      for( var i=0;i<data.length;i++){
        var cur_o = data[i];

        if( cur_o[key_parent] === 0 ){
          da_lv1.push(cur_o);
        }else{
          if( typeof da_lv2[cur_o[key_parent]] == 'undefined' ){
            da_lv2[cur_o[key_parent]]=[];
          }
          da_lv2[cur_o[key_parent]].push(cur_o);
        }
      }

      for( var j=0;j<da_lv1.length;j++){
        if( da_lv2[da_lv1[j][key_id]] instanceof Array ){
          da_lv1[j].has_child = 1;
          da_lv1[j].childs = da_lv2[da_lv1[j][key_id]];
        }else{
          da_lv1[j].has_child = 0;
          da_lv1[j].childs = [];
        }
      }

      x$list_lv1.setData(da_lv1);

      console.log(da_lv1);

      x$flyout.addCls('fo_inited');
    };



    if( !has_class(x$flyout,'fo_inited') ){

      send_request( {
        api:'opt_industry',
        method:'POST',
        params:{
          pageSize:1000
        },
        success:function(result, request){
          if( result.success ){
            switch( result.code ){
              case '0000':
                //成功
                init_fo(result.data);
                break;
              case '1001':
                //失败
                break;
              default:
                toast("errCode:"+result.code);
                break;
            }
          }else{

          }
        },
        fail:function(result){
          toast("您的网络似乎有点问题，请稍候再试！");
        },
        text:'加载中',
        silent:false,
        trigger:_this,
        check_login:false
      } );


    }








  },

  init_fo_type: function() {
    var x$flyout = x$('cnear_fo_type');
    var x$list = x$('cnear_filter_list_type');



    var _this = this;


    var init_fo = function(data){

      console.log(data);

      data.enterpriseType.unshift({
        has_child:0,
        value:0,
        name:'重置',
        is_reset:true
      });

      set_store_data( x$list,data.enterpriseType );
      x$flyout.addCls('fo_inited');
    };

    if( !has_class(x$flyout,'fo_inited') ){

      send_request( {
        api:'enum',
        method:'POST',
        params:{
          pageSize:1000
        },
        success:function(result, request){
          if( result.success ){
            switch( result.code ){
              case '0000':
                //成功
                init_fo(result.data);
                break;
              case '1001':
                //失败
                break;
              default:
                toast("errCode:"+result.code);
                break;
            }
          }else{

          }
        },
        fail:function(result){
          toast("您的网络似乎有点问题，请稍候再试！");
        },
        text:'加载中',
        silent:false,
        trigger:_this,
        check_login:false
      } );


    }








  },

  init_fo_school: function() {
    var x$flyout = x$('cnear_fo_school');
    var x$list = x$('cnear_filter_list_school');




    var _this = this;


    var init_fo = function(data){
      set_store_data( x$list,data );
      x$flyout.addCls('fo_inited');
    };

    if( !has_class(x$flyout,'fo_inited') ){

      send_request( {
        api:'opt_school',
        method:'POST',
        params:{
          pageSize:1000
        },
        success:function(result, request){
          if( result.success ){
            switch( result.code ){
              case '0000':
                //成功
                init_fo(result.data);
                break;
              case '1001':
                //失败
                break;
              default:
                toast("errCode:"+result.code);
                break;
            }
          }else{

          }
        },
        fail:function(result){
          toast("您的网络似乎有点问题，请稍候再试！");
        },
        text:'加载中',
        silent:false,
        trigger:_this,
        check_login:false
      } );


    }








  },

  set_industry: function(value, text) {
    var fo_id = 'cnear_fo_industry';
    var btn_id = 'cnear_btn_industry';

    var x$fo = x$(fo_id);
    var x$btn = x$(btn_id);



    if( value === 0 ){
      set_data( x$fo,'value',null );
      set_data( x$fo,'label',null );
      x$btn.setText('选择行业');
    }else{
      set_data( x$fo,'value',value );
      set_data( x$fo,'label',text );
      x$btn.setText(text);
    }

    this.reset_fo();
    this.update();
  },

  set_type: function(value, text) {
    var fo_id = 'cnear_fo_type';
    var btn_id = 'cnear_btn_type';

    var x$fo = x$(fo_id);
    var x$btn = x$(btn_id);



    if( value === 0 ){
      set_data( x$fo,'value',null );
      set_data( x$fo,'label',null );
      x$btn.setText('企业性质');
    }else{
      set_data( x$fo,'value',value );
      set_data( x$fo,'label',text );
      x$btn.setText(text);
    }

    this.reset_fo();
    this.update();
  },

  set_school: function(value, text) {
    var fo_id = 'cnear_fo_school';
    var btn_id = 'cnear_btn_school';

    var x$fo = x$(fo_id);
    var x$btn = x$(btn_id);


    set_data( 'cnear_fo_school','value',value );
    set_data( 'cnear_fo_school','label',text );

    x$btn.setText(text);

    this.reset_fo();
    this.update();
  },

  reset_fo: function() {
    var x$industry = x$('cnear_fo_industry');
    var x$type = x$('cnear_fo_type');
    var x$school = x$('cnear_fo_school');


    var x$btn_industry = x$('cnear_btn_industry');
    var x$btn_type = x$('cnear_btn_type');
    var x$btn_school = x$('cnear_btn_school');


    x$industry.hide();
    x$type.hide();
    x$school.hide();


    clr_active(x$btn_industry);
    clr_active(x$btn_type);
    clr_active(x$btn_school);
  }

});