/*
 * File: app/view/CompanyMap.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.view.CompanyMap', {
  extend: 'Ext.Container',

  requires: [
    'Ext.TitleBar',
    'Ext.Button',
    'Ext.Panel'
  ],

  config: {
    layout: 'fit',
    items: [
      {
        xtype: 'titlebar',
        cls: 'zjs-bg-green',
        docked: 'top',
        ui: 'zjs',
        title: '附近企业',
        items: [
          {
            xtype: 'button',
            height: 30,
            itemId: 'mybutton23',
            ui: 'plain',
            width: 30,
            icon: '',
            iconCls: 'zjs-icon-back',
            text: 'back'
          }
        ]
      },
      {
        xtype: 'panel',
        cls: 'map_content',
        hidden: false,
        html: '<div id="c_near_map" style="width:100%;height:100%"></div>'
      }
    ],
    listeners: [
      {
        fn: 'onMybutton23Tap311',
        event: 'tap',
        delegate: '#mybutton23'
      }
    ]
  },

  onMybutton23Tap311: function(button, e, eOpts) {
    button.up('navigationview').pop();
  },

  initialize: function() {
    this.callParent();

  },

  update: function(_p) {
    var _this = this;

    var request_data = function(){

      var params = {
        pageSize:100,
        location:JSON.stringify(fix_location(get_location())),
        distance:1000
      };

      //toast('Use Location '+get_location().lat+' '+get_location().lng);

      send_request( {
        api:'c_near',
        method:'POST',
        params:params,
        success:function(result, request){
          if( result.success ){
            switch( result.code ){
              case '0000':
                //成功
                console.log(result);
                _this.build_page(result.data);
                break;
              case '1001':
                //失败
                break;
              default:
                toast("errCode:"+result.code);
                break;
            }
          }else{

          }
        },
        fail:function(result){
          toast("您的网络似乎有点问题，请稍候再试！");
        },
        text:'加载中',
        silent:false,
        trigger:_this,
        check_login:true
      } );


    };



    var geo_check = function(){

      if( need_geo_update() ){
        update_location(function(loc,status){

          if(loc){
            request_data();
          }else{
            toast('抱歉，无法获取您的当前位置。');
          }

        },{
          silent:false
        });

      }else{
        request_data();
      }


    };





    if( typeof BMap == 'undefined' ){
      jQuery.getScript(_G.BAIDU_SCRIPT,function(data,status,xhr){
        geo_check();
      });
    }else{
      geo_check();
    }



  },

  build_page: function(data) {

    console.log('build');

    console.log(data);


    if( typeof BMap == 'undefined' ){
      return;
    }else{
      var map = new BMap.Map("c_near_map");

      var loc = get_location();

      map.centerAndZoom(new BMap.Point(loc.lng,loc.lat), 14);

      //toast('Find Location '+loc.lng+' '+loc.lat);

      var points_da = [];

      console.log(data);

      data.push({
        locationX:loc.lng,
        locationY:loc.lat,
        companyName:'您的位置'
      });


      console.log('loc data');
      console.log(data);

      for( var i=0;i<data.length;i++ ){
        //var location = JSON.parse(data[i].location);

        var lng = data[i].locationX;
        var lat = data[i].locationY;

        console.log( lng + ' ' + lat );

        (function(){
          var point = new BMap.Point(lng,lat);
          var info_window = new BMap.InfoWindow(data[i].companyName);

          var marker = new BMap.Marker(point);
          map.addOverlay(marker);

          marker.addEventListener("click", function(){this.openInfoWindow(info_window);});

          points_da.push(point);

        })();

      }

      if( points_da.length ){
        map.setViewport(points_da);
      }

    }
  }

});