/*
 * File: app/view/Feedback.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.view.Feedback', {
  extend: 'Ext.Container',

  requires: [
    'Ext.form.Panel',
    'Ext.field.TextArea',
    'Ext.TitleBar',
    'Ext.Button'
  ],

  config: {
    cls: 'zjs',
    layout: 'card',
    items: [
      {
        xtype: 'formpanel',
        scrollable: 'vertical',
        items: [
          {
            xtype: 'textareafield',
            height: 150,
            id: 'reply_field',
            placeHolder: '  请输入您的意见反馈'
          }
        ]
      },
      {
        xtype: 'titlebar',
        cls: 'zjs-bg-green',
        docked: 'top',
        ui: 'zjs',
        title: '意见反馈',
        items: [
          {
            xtype: 'button',
            height: 30,
            itemId: 'mybutton23',
            ui: 'plain',
            width: 30,
            icon: '',
            iconCls: 'zjs-icon-back',
            text: 'back'
          },
          {
            xtype: 'button',
            align: 'right',
            itemId: 'mybutton44',
            text: '提交'
          }
        ]
      }
    ],
    listeners: [
      {
        fn: 'onMybutton23Tap',
        event: 'tap',
        delegate: '#mybutton23'
      },
      {
        fn: 'onMybutton44Tap',
        event: 'tap',
        delegate: '#mybutton44'
      }
    ]
  },

  onMybutton23Tap: function(button, e, eOpts) {
    button.up('navigationview').pop();
  },

  onMybutton44Tap: function(button, e, eOpts) {

    var x$field = x$('reply_field');


    var value = jQuery.trim(x$field.getValue());


    console.log(value);


    if( value == '' ){
      toast('请输入意见。');
    }else{



      send_request( {
        api:'feedback',
        method:'POST',
        params:{
          feedbackContent:fix_cn(value)
        },
        success:function(result, request){
          if( result.success ){
            switch( result.code ){
              case '0000':
                //成功
                toast('您的意见已提交，感谢您的支持！');
                button.up('navigationview').pop();
                break;
              case '1001':
                //失败
                toast('提交失败，请稍后再试。');
                break;
              default:
                toast("errCode:"+result.code);
                break;
            }
          }else{

          }
        },
        fail:function(result){
          toast("您的网络似乎有点问题，请稍候再试！");
        },
        text:'加载中',
        silent:false,
        trigger:button,
        check_login:false
      } );






    }

  },

  update: function(_p) {

  },

  initialize: function() {
    this.callParent();




  }

});