/*
 * File: app/view/Home.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.view.Home', {
  extend: 'Ext.Container',
  alias: 'widget.home',

  requires: [
    'Ext.TitleBar',
    'Ext.Button',
    'Ext.Panel',
    'Ext.field.Search',
    'Ext.dataview.DataView',
    'Ext.XTemplate'
  ],

  config: {
    cls: 'zjs',
    id: 'Home',
    layout: 'fit',
    items: [
      {
        xtype: 'titlebar',
        cls: 'zjs-bg-green',
        docked: 'top',
        ui: 'zjs',
        title: '优渡人才',
        items: [
          {
            xtype: 'button',
            id: 'btn-home-nav-city',
            itemId: 'mybutton19',
            text: '上海'
          },
          {
            xtype: 'button',
            align: 'right',
            id: 'btn-home-nav-login',
            itemId: 'mybutton20',
            text: '登录'
          },
          {
            xtype: 'button',
            align: 'right',
            id: 'btn-home-nav-usercenter',
            itemId: 'mybutton21',
            text: '个人中心'
          }
        ]
      },
      {
        xtype: 'panel',
        scrollable: false,
        items: [
          {
            xtype: 'panel',
            cls: 'hp-search',
            height: 50,
            padding: 0,
            layout: 'hbox',
            items: [
              {
                xtype: 'panel',
                flex: 1,
                cls: 'col-search',
                height: 50,
                padding: '5px 0 5px 5px',
                layout: 'fit',
                items: [
                  {
                    xtype: 'searchfield',
                    id: 'home-search-keywords',
                    labelWidth: 0,
                    name: '',
                    placeHolder: '输入职位名称/公司名称'
                  }
                ]
              },
              {
                xtype: 'panel',
                cls: 'col-btn',
                height: 50,
                width: 50,
                layout: 'fit',
                items: [
                  {
                    xtype: 'button',
                    itemId: 'mybutton117',
                    iconCls: 'zjs-icon-search',
                    text: '搜索'
                  }
                ]
              },
              {
                xtype: 'panel',
                cls: 'col-btn',
                height: 50,
                width: 50,
                layout: 'fit',
                items: [
                  {
                    xtype: 'button',
                    itemId: 'mybutton118',
                    iconCls: 'zjs-icon-add',
                    text: '订阅'
                  }
                ]
              }
            ]
          },
          {
            xtype: 'panel',
            cls: 'hp-icon-menu',
            height: 100,
            layout: 'hbox',
            items: [
              {
                xtype: 'panel',
                flex: 1,
                cls: 'icon-button',
                layout: 'fit',
                items: [
                  {
                    xtype: 'button',
                    cls: 'btn-icon-speaker',
                    height: 100,
                    itemId: 'mybutton9',
                    width: '',
                    text: '宣讲会'
                  }
                ]
              },
              {
                xtype: 'panel',
                flex: 1,
                cls: 'icon-button',
                layout: 'fit',
                items: [
                  {
                    xtype: 'button',
                    cls: 'btn-icon-message',
                    height: 100,
                    itemId: 'mybutton10',
                    width: '',
                    text: '招聘会'
                  }
                ]
              },
              {
                xtype: 'panel',
                flex: 1,
                cls: 'icon-button',
                layout: 'fit',
                items: [
                  {
                    xtype: 'button',
                    cls: 'btn-icon-star',
                    height: 100,
                    itemId: 'mybutton11',
                    width: '',
                    text: '热门企业'
                  }
                ]
              },
              {
                xtype: 'panel',
                flex: 1,
                cls: 'icon-button',
                layout: 'fit',
                items: [
                  {
                    xtype: 'button',
                    cls: 'btn-icon-job',
                    height: 100,
                    itemId: 'mybutton12',
                    width: '',
                    text: '实习职位'
                  }
                ]
              }
            ]
          },
          {
            xtype: 'dataview',
            cls: 'zjs-listview-2line',
            itemId: 'mydataview37',
            minHeight: 180,
            scrollable: false,
            disableSelection: true,
            itemTpl: [
              '<div class="li">',
              '  <div class="c">',
              '    <h4>{title}</h4>',
              '    <p>{desc}</p>',
              '  </div>',
              '  <div class="i">',
              '    <span></span>',
              '  </div>',
              '</div>'
            ],
            store: 'hpNav'
          }
        ]
      }
    ],
    listeners: [
      {
        fn: 'onMybutton19Tap1',
        event: 'tap',
        delegate: '#btn-home-nav-city'
      },
      {
        fn: 'onMybutton19Tap11',
        event: 'tap',
        delegate: '#btn-home-nav-login'
      },
      {
        fn: 'onMybutton19Tap111',
        event: 'tap',
        delegate: '#btn-home-nav-usercenter'
      },
      {
        fn: 'onMybutton117Tap',
        event: 'tap',
        delegate: '#mybutton117'
      },
      {
        fn: 'onMybutton118Tap',
        event: 'tap',
        delegate: '#mybutton118'
      },
      {
        fn: 'onMybutton9Tap',
        event: 'tap',
        delegate: '#mybutton9'
      },
      {
        fn: 'onMybutton10Tap',
        event: 'tap',
        delegate: '#mybutton10'
      },
      {
        fn: 'onMybutton11Tap',
        event: 'tap',
        delegate: '#mybutton11'
      },
      {
        fn: 'onMybutton12Tap',
        event: 'tap',
        delegate: '#mybutton12'
      },
      {
        fn: 'onMydataview37ItemTap',
        event: 'itemtap',
        delegate: '#mydataview37'
      },
      {
        fn: 'onHomePainted',
        event: 'painted'
      }
    ]
  },

  onMybutton19Tap1: function(button, e, eOpts) {
    change_page('CityChooser_CNL',button);
  },

  onMybutton19Tap11: function(button, e, eOpts) {
    change_page('Login',button);
  },

  onMybutton19Tap111: function(button, e, eOpts) {
    x$('TabFrame').setActiveItem(2);
  },

  onMybutton117Tap: function(button, e, eOpts) {
    var keywords = x$('home-search-keywords').getValue();

    if(keywords){
      change_page('HomeSearchResult',button,{keywords:fix_cn(keywords)});
    }else{
      toast("请输入需要搜索的关键词。");
    }

  },

  onMybutton118Tap: function(button, e, eOpts) {
    change_page('PositionSubscribe',button);
  },

  onMybutton9Tap: function(button, e, eOpts) {
    change_page('CampusTalk',button);
  },

  onMybutton10Tap: function(button, e, eOpts) {
    change_page('Recruitment',button);
  },

  onMybutton11Tap: function(button, e, eOpts) {
    change_page('CompanyHot',button);
  },

  onMybutton12Tap: function(button, e, eOpts) {
    change_page('InternPosition',button);
  },

  onMydataview37ItemTap: function(dataview, index, target, record, e, eOpts) {

    var data = record.data;

    console.log(data);


    switch( data.xindex ){

      case 0:
        change_page('PositionSubscribe',dataview);
        break;
      case 1:
        //var page = Ext.create('ZJ02.view.CampusTalk', {fullscreen: true});
        //dataview.up('tabpanel').setActiveItem(2);
        change_page( 'ResumeCenter',dataview );
        break;
      case 2:
        //var page = Ext.create('ZJ02.view.CampusTalk', {fullscreen: true});
        dataview.up('tabpanel').setActiveItem(3);
        break;

    }
  },

  onHomePainted: function(element, eOpts) {
    if( navigator.splashscreen ){
      window.setTimeout(function(){
        navigator.splashscreen.hide();
      },3000);
    }
  },

  initialize: function() {
    this.callParent();
    this.update();



  },

  update: function() {

    if( is_login() ){
      x$('btn-home-nav-login').hide();
      x$('btn-home-nav-usercenter').show();
    }else{
      x$('btn-home-nav-login').show();
      x$('btn-home-nav-usercenter').hide();
    }

    var city = get_city();

    if( city ){
      x$('btn-home-nav-city').setText(city.name);
    }else{
      x$('btn-home-nav-city').setText('选择城市');
    }

  }

});