/*
 * File: app/view/InternPositionDetail.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.view.InternPositionDetail', {
  extend: 'Ext.Container',

  requires: [
    'Ext.TitleBar',
    'Ext.Button',
    'Ext.Panel',
    'Ext.SegmentedButton',
    'Ext.dataview.List',
    'Ext.XTemplate'
  ],

  config: {
    cls: 'zjs',
    layout: 'card',
    items: [
      {
        xtype: 'titlebar',
        cls: 'zjs-bg-green',
        docked: 'top',
        ui: 'zjs',
        title: '职位详情',
        items: [
          {
            xtype: 'button',
            height: 30,
            itemId: 'mybutton24',
            ui: 'plain',
            width: 30,
            icon: '',
            iconCls: 'zjs-icon-back',
            text: 'back'
          }
        ]
      },
      {
        xtype: 'panel',
        html: '',
        id: 'i_p_d_scp',
        scrollable: 'vertical',
        items: [
          {
            xtype: 'panel',
            cls: 'detail_panel content_con',
            id: 'intern_pos_detail_line_1',
            padding: '0.2em 0.7em',
            layout: 'hbox'
          },
          {
            xtype: 'panel',
            cls: 'detail_content  content_con',
            id: 'intern_pos_detail_line_2',
            padding: '1em'
          }
        ]
      },
      {
        xtype: 'segmentedbutton',
        cls: 'zjs-segment-btn-bottom',
        docked: 'bottom',
        height: 50,
        defaults: {
          flex: 1
        },
        items: [
          {
            xtype: 'button',
            cls: 'btn-green',
            itemId: 'btn_i_p_d_apply_job',
            iconCls: 'zjs-icon-copy',
            text: '申请'
          },
          {
            xtype: 'button',
            cls: 'btn-blue',
            itemId: 'btn_i_p_d_add_fav',
            iconCls: 'zjs-icon-star',
            text: '收藏'
          }
        ]
      },
      {
        xtype: 'container',
        centered: true,
        height: 250,
        hidden: true,
        itemId: 'pop_resume',
        width: 300,
        modal: true,
        items: [
          {
            xtype: 'titlebar',
            docked: 'top',
            title: '选择简历',
            items: [
              {
                xtype: 'button',
                align: 'right',
                itemId: 'mybutton42',
                text: '取消'
              }
            ]
          },
          {
            xtype: 'list',
            height: 200,
            itemId: 'pop_resume_list',
            width: 300,
            disableSelection: true,
            itemTpl: [
              '<div>{text}</div>'
            ]
          }
        ]
      }
    ],
    listeners: [
      {
        fn: 'onMybutton23Tap311111',
        event: 'tap',
        delegate: '#mybutton24'
      },
      {
        fn: 'onBtn_i_p_d_apply_jobTap',
        event: 'tap',
        delegate: '#btn_i_p_d_apply_job'
      },
      {
        fn: 'onBtn_i_p_d_add_favTap',
        event: 'tap',
        delegate: '#btn_i_p_d_add_fav'
      },
      {
        fn: 'onMybutton42Tap1',
        event: 'tap',
        delegate: '#mybutton42'
      },
      {
        fn: 'onPop_resume_listItemTap1',
        event: 'itemtap',
        delegate: '#pop_resume_list'
      }
    ]
  },

  onMybutton23Tap311111: function(button, e, eOpts) {
    button.up('navigationview').pop();
  },

  onBtn_i_p_d_apply_jobTap: function(button, e, eOpts) {
    var _this = this;

    if( _this.resume_data && _this.resume_data.length>0 ){
      var x$pop_resume = _this.down('#pop_resume');
      x$pop_resume.show();
    }else{
      toast('您尚未创建简历。请先去优渡网创建简历。');
    }




  },

  onBtn_i_p_d_add_favTap: function(button, e, eOpts) {
    var _this = this;


    if( _this.page_data && _this.page_data.positionId ){

      send_request( {
        api:'p_fav',
        method:'POST',
        params:{
          positionId:_this.page_data.positionId
        },
        success:function(result, request){
          //if( result.success ){
            switch( result.code ){
              case '0000':
                //成功
                if( result.alreadyCollect ){
                  toast('您已收藏过该职位。');
                }else{
                  toast('您已收藏成功。');
                }
                break;
              case '1001':
                //失败
                break;
              default:
                toast("errCode:"+result.code);
                break;
            }
          //}else{

          //}
        },
        fail:function(result){
          toast("您的网络似乎有点问题，请稍候再试！");
        },
        text:'加载中',
        silent:false,
        trigger:button,
        check_login:false
      } );

    }else{
      toast('暂无可收藏的职位。');
    }


  },

  onMybutton42Tap1: function(button, e, eOpts) {
    button.up('#pop_resume').hide();
  },

  onPop_resume_listItemTap1: function(dataview, index, target, record, e, eOpts) {
    var _this = this;

    var resume_id = window.resume_private_id;

    var newValue = record.data.value;

    if( newValue == 0 ){
      toast('请选择需要申请的简历。');
    }else{

      if( _this.page_data && _this.page_data.positionId ){

        send_request( {
          api:'p_apply',
          method:'POST',
          params:{
            positionId:_this.page_data.positionId,
            resumeId:newValue
          },
          success:function(result, request){
            //if( result.success ){
              switch( result.code ){
                case '0000':
                  //成功
                  if( result.alreadyApply ){
                    toast('您一周之内已经申请过该职位。');
                  }else{
                    toast('您的职位申请已提交。');
                  }
                  break;
                case '1001':
                  //失败
                  break;
                default:
                  toast("errCode:"+result.code);
                  break;
              }
            //}else{

            //}
          },
          fail:function(result){
            toast("您的网络似乎有点问题，请稍候再试！");
          },
          text:'加载中',
          silent:false,
          trigger:_this,
          check_login:false
        } );

      }else{
        toast('暂无可申请的职位。');
      }




    }





    var x$pop_resume = _this.down('#pop_resume');
    x$pop_resume.hide();


  },

  initialize: function() {
    this.callParent();
  },

  update: function(_p) {
    var _this = this;


    console.log(_p);

    if( _p && _p.positionId ){

      send_request( {
        api:'p_detail',
        method:'POST',
        params:{
          pageSize:100,
          positionId:_p.positionId
        },
        success:function(result, request){
          if( result.success ){
            switch( result.code ){
              case '0000':
                //成功
                console.log(result);
                _this.page_data = result.data;
                _this.build_page(result.data);
                break;
              case '1001':
                //失败
                break;
              default:
                toast("errCode:"+result.code);
                break;
            }
          }else{

          }
        },
        fail:function(result){
          toast("您的网络似乎有点问题，请稍候再试！");
        },
        text:'加载中',
        silent:false,
        trigger:_this,
        check_login:true
      } );

    }



  },

  build_page: function(data) {
    var x$line1 = x$('intern_pos_detail_line_1');
    var x$line2 = x$('intern_pos_detail_line_2');




    var date_ra = parse_date(data.refreshTime,'date_');
    jQuery.extend( data,date_ra );

    get_enum(function(enum_da){
      var educationType = enum_da.educationType;

      var edu_code2name = {};

      for( var i=0;i<educationType.length;i++ ){
        edu_code2name[educationType[i].code] = educationType[i].name;
      }

      var line1_html = ' <h4>职位名称：'+(data.positionName||'暂无')+'</h4> <ul class="c2x c2x_fit">   <li>招聘人数：'+(data.hirNumber||'暂无')+'</li>   <li>薪资待遇：'+(data.salary||'暂无')+'</li>   <li>发布时间：'+(data.date_fullyeardate||'暂无')+'</li>   <li>学历要求：'+(data.education?edu_code2name[data.education]:'暂无')+'</li>   <li>工作经验：'+(data.workExp?data.workExp+'年':'暂无')+'</li>   <li>工作地点：'+(data.areaName||'暂无')+'</li> </ul>';
      var line2_html = ' <h4>职位要求</h4> <p>'+(data.description||'暂无')+'</p>';

      x$line1.setHtml(line1_html);
      x$line2.setHtml(line2_html);



      refresh_scroll(x$('i_p_d_scp'));


    });




    var _this = this;

    var x$pop_resume_list = _this.down('#pop_resume_list');


    send_request( {
      api:'resume_list',
      method:'POST',
      params:{
        pageSize:100
      },
      success:function(result, request){
        if( result.success ){
          switch( result.code ){
            case '0000':
              //成功
              console.log(result);
              _this.resume_data = result.data;
              if( result.data && result.data.length>0 ){
                var fe_da = [];
                for( var i=0;i<result.data.length;i++ ){
                  fe_da.push({
                    text:result.data[i].resumeTitle,
                    value:result.data[i].resumeId
                  });
                }


                set_store_data(x$pop_resume_list,fe_da);

              }
              break;
            case '1001':
              //失败
              break;
            default:
              toast("errCode:"+result.code);
              break;
          }
        }else{

        }
      },
      fail:function(result){
        toast("您的网络似乎有点问题，请稍候再试！");
      },
      text:'加载中',
      silent:false,
      trigger:_this,
      check_login:true
    } );




  }

});