/*
 * File: app/view/JobBookApplyList.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.view.JobBookApplyList', {
  extend: 'Ext.Container',

  requires: [
    'Ext.TitleBar',
    'Ext.Button',
    'Ext.XTemplate',
    'Ext.SegmentedButton',
    'Ext.dataview.List'
  ],

  config: {
    cls: 'zjs',
    layout: 'card',
    items: [
      {
        xtype: 'titlebar',
        cls: 'zjs-bg-green',
        docked: 'top',
        ui: 'zjs',
        title: '职位申请列表',
        items: [
          {
            xtype: 'button',
            height: 30,
            itemId: 'mybutton23',
            ui: 'plain',
            width: 30,
            icon: '',
            iconCls: 'zjs-icon-back',
            text: 'back'
          }
        ]
      },
      {
        xtype: 'dataview',
        cls: 'zjs-listview-jobapplylist',
        id: 'list-job-book-apply',
        itemId: 'mydataview3',
        minHeight: 180,
        scrollable: 'vertical',
        allowDeselect: true,
        disableSelection: false,
        mode: 'MULTI',
        itemTpl: [
          '<div class="li">',
          '  <div class="d">',
          '  	<span></span>',
          '  </div>',
          '  <div class="c">',
          '  	<h4>{positionName}</h4>',
          '    <p>{companyName}</p>',
          '  </div>',
          '  <div class="i btn_detail">',
          '  	<span></span>',
          '  </div>',
          '  <div class="b">',
          '    <div class="count"><span>{salary}</span></div>',
          '    <div class="count"><span>{date_localfulldate}</span></div>',
          '  </div>',
          '</div>'
        ]
      },
      {
        xtype: 'segmentedbutton',
        cls: 'zjs-segment-btn-bottom',
        docked: 'bottom',
        height: 50,
        defaults: {
          flex: 1
        },
        items: [
          {
            xtype: 'button',
            cls: 'btn-green',
            itemId: 'mybutton72',
            iconCls: 'zjs-icon-copy',
            text: '全部申请'
          },
          {
            xtype: 'button',
            cls: 'btn-blue',
            itemId: 'mybutton73',
            iconCls: 'zjs-icon-star',
            text: '全部收藏'
          }
        ]
      },
      {
        xtype: 'container',
        centered: true,
        height: 250,
        hidden: true,
        itemId: 'pop_resume',
        width: 300,
        modal: true,
        items: [
          {
            xtype: 'titlebar',
            docked: 'top',
            title: '选择简历',
            items: [
              {
                xtype: 'button',
                align: 'right',
                itemId: 'mybutton42',
                text: '取消'
              }
            ]
          },
          {
            xtype: 'list',
            height: 200,
            itemId: 'pop_resume_list',
            width: 300,
            disableSelection: true,
            itemTpl: [
              '<div>{text}</div>'
            ]
          }
        ]
      }
    ],
    listeners: [
      {
        fn: 'onMybutton23Tap',
        event: 'tap',
        delegate: '#mybutton23'
      },
      {
        fn: 'onMydataview2ItemTap1',
        event: 'itemtap',
        delegate: '#list-job-book-apply'
      },
      {
        fn: 'onMybutton72Tap',
        event: 'tap',
        delegate: '#mybutton72'
      },
      {
        fn: 'onMybutton73Tap',
        event: 'tap',
        delegate: '#mybutton73'
      },
      {
        fn: 'onMybutton42Tap1',
        event: 'tap',
        delegate: '#mybutton42'
      },
      {
        fn: 'onPop_resume_listItemTap1',
        event: 'itemtap',
        delegate: '#pop_resume_list'
      }
    ]
  },

  onMybutton23Tap: function(button, e, eOpts) {
    button.up('navigationview').pop();
  },

  onMydataview2ItemTap1: function(dataview, index, target, record, e, eOpts) {

    var item_data = record.data;

    if( jQuery(e.target).parents('.btn_detail').length || jQuery(e.target).is('.btn_detail') ){
      change_page('CompanyDetail',dataview,{companyId:item_data.companyId});
      return false;
    }

  },

  onMybutton72Tap: function(button, e, eOpts) {
    var _this = this;





    var x$list = x$('list-job-book-apply');

    var x$items = x$list.getSelection();

    var selected_ids = [];
    for(var i=0; i<x$items.length; i++){
      selected_ids.push(x$items[i].data.positionId);

    }


    if(selected_ids.length){

      if( _this.resume_data && _this.resume_data.length>0 ){

        var x$pop_resume = _this.down('#pop_resume');
        x$pop_resume.show();


      }else{
        toast('您尚未创建简历。请先去优渡网创建简历。');
      }

    }else{
      toast('请选择您要申请的职位。');
    }





    return;



  },

  onMybutton73Tap: function(button, e, eOpts) {

    var x$list = x$('list-job-book-apply');

    var x$items = x$list.getSelection();


    var selected_ids = [];
    for(var i=0; i<x$items.length; i++){
      selected_ids.push(x$items[i].data.positionId);

    }



    if(selected_ids.length){
      send_request( {
        api:'p_fav',
        method:'POST',
        params:{
          positionId:selected_ids.join(',')
        },
        success:function(result, request){

          //if( result.success ){
            switch( result.code ){
              case '0000':
                //成功
                if( result.alreadyCollect ){
                  toast('您已收藏过该职位。');
                }else{
                  toast('您已收藏成功。');
                }
                break;
              case '1001':
                //失败
                break;
              default:
                toast("errCode:"+result.code);
                break;
            }
          //}else{

          //}

        },
        fail:function(result){
          toast("您的网络似乎有点问题，请稍候再试！");
        },
        text:'加载中',
        silent:false,
        trigger:button,
        check_login:false
      } );
    }else{
      toast('请选择您要收藏的职位。');
    }


  },

  onMybutton42Tap1: function(button, e, eOpts) {
    button.up('#pop_resume').hide();
  },

  onPop_resume_listItemTap1: function(dataview, index, target, record, e, eOpts) {


    var _this = this;


    var x$list = x$('list-job-book-apply');

    var x$items = x$list.getSelection();

    var _this = this;

    var selected_ids = [];
    for(var i=0; i<x$items.length; i++){
      selected_ids.push(x$items[i].data.positionId);
    }

    var newValue = record.data.value;


    if( newValue === 0 ){
      toast('请选择需要申请的简历。');
    }else{

      if( selected_ids.length ){

        send_request( {
          api:'p_apply',
          method:'POST',
          params:{
            positionId:selected_ids.join(','),
            resumeId:newValue
          },
          success:function(result, request){
            //if( result.success ){
              switch( result.code ){
                case '0000':
                  //成功
                  if( result.alreadyApply ){
                    toast('您一周之内已经申请过该职位。');
                  }else{
                    toast('您的职位申请已提交。');
                  }
                  break;
                case '1001':
                  //失败
                  break;
                default:
                  toast("errCode:"+result.code);
                  break;
              }
            //}else{

            //}
          },
          fail:function(result){
            toast("您的网络似乎有点问题，请稍候再试！");
          },
          text:'加载中',
          silent:false,
          trigger:_this,
          check_login:false
        } );

      }else{
        toast('暂无可申请的职位。');
      }


    }




    var x$pop_resume = _this.down('#pop_resume');
    x$pop_resume.hide();

  },

  initialize: function() {
    this.callParent();
  },

  update: function(_p) {
    var _this = this;


    if( _p && _p.subscriptionId )


    send_request( {
      api:'msg.job_subscribe.pos_list',
      method:'POST',
      params:{
        subscriptionId:_p.subscriptionId,
        pageSize:100
      },
      success:function(result, request){
        if( result.success ){
          switch( result.code ){
            case '0000':
              //成功
              console.log(result);
              _this.build_list(result.data);
              break;
            case '1001':
              //失败
              break;
            default:
              toast("errCode:"+result.code);
              break;
          }
        }else{

        }
      },
      fail:function(result){
        toast("您的网络似乎有点问题，请稍候再试！");
      },
      text:'加载中',
      silent:false,
      trigger:_this,
      check_login:true
    } );





    var x$pop_resume_list = _this.down('#pop_resume_list');

    send_request( {
      api:'resume_list',
      method:'POST',
      params:{
        pageSize:100
      },
      success:function(result, request){
        if( result.success ){
          switch( result.code ){
            case '0000':
              //成功
              console.log(result);
              _this.resume_data = result.data;
              if( result.data && result.data.length>0 ){
                var fe_da = [];
                for( var i=0;i<result.data.length;i++ ){
                  fe_da.push({
                    text:result.data[i].resumeTitle,
                    value:result.data[i].resumeId
                  });
                }

                set_store_data(x$pop_resume_list,fe_da);

              }
              break;
            case '1001':
              //失败
              break;
            default:
              toast("errCode:"+result.code);
              break;
          }
        }else{

        }
      },
      fail:function(result){
        toast("您的网络似乎有点问题，请稍候再试！");
      },
      text:'加载中',
      silent:false,
      trigger:_this,
      check_login:true
    } );




  },

  build_list: function(data) {
    var x$list = x$('list-job-book-apply');


    if(data && data.length){

      for( var i=0;i<data.length;i++ ){
        var date_ra = parse_date(data[i].refreshiTime,'date_');
        jQuery.extend( data[i],date_ra );
      }


      x$list.removeCls('zj-list-no-data');
      x$list.setData(data);
    }else{
      x$list.addCls('zj-list-no-data');
      x$list.removeAll();
    }


    refresh_scroll(x$list);
  }

});