/*
 * File: app/view/JobFavourite.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.view.JobFavourite', {
  extend: 'Ext.Container',

  requires: [
    'Ext.TitleBar',
    'Ext.Button',
    'Ext.dataview.DataView',
    'Ext.XTemplate'
  ],

  config: {
    cls: 'zjs',
    layout: 'card',
    items: [
      {
        xtype: 'titlebar',
        cls: 'zjs-bg-blue',
        docked: 'top',
        ui: 'zjs',
        title: '职位收藏',
        items: [
          {
            xtype: 'button',
            height: 30,
            itemId: 'mybutton23',
            ui: 'plain',
            width: 30,
            icon: '',
            iconCls: 'zjs-icon-back',
            text: 'back'
          }
        ]
      },
      {
        xtype: 'container',
        cls: 'zj-list-no-data',
        hidden: true,
        itemId: 'nodata'
      },
      {
        xtype: 'dataview',
        cls: 'zjs-listview-3line-c-del',
        id: 'list_uc_fav_job',
        itemId: 'mydataview4',
        minHeight: 180,
        scrollable: 'vertical',
        disableSelection: true,
        itemTpl: [
          '<div class="li">',
          '  <div class="c list_c_job_favourite">',
          '    <div class="cw">',
          '      <h4>{posName}</h4>',
          '      <div class="cp">',
          '        <div class="cl">',
          '          <p>{enterpriseName}</p>',
          '          <p><em>{date_fullyeardate}</em></p>',
          '        </div>',
          '        <div class="cr">',
          '          <p>薪资</p>',
          '          <p>{salaryName}</p>',
          '        </div>',
          '      </div>',
          '    </div>',
          '  </div>',
          '  <div class="i"> <span></span> </div>',
          '  <div class="del"> <span></span> </div>',
          '</div>',
          ''
        ]
      }
    ],
    listeners: [
      {
        fn: 'onMybutton23Tap',
        event: 'tap',
        delegate: '#mybutton23'
      },
      {
        fn: 'onList_uc_fav_jobItemTap',
        event: 'itemtap',
        delegate: '#list_uc_fav_job'
      }
    ]
  },

  onMybutton23Tap: function(button, e, eOpts) {
    var x$last_page = button.up('navigationview').pop();
    x$last_page.update();
  },

  onList_uc_fav_jobItemTap: function(dataview, index, target, record, e, eOpts) {

    var item_data = record.data;

    var _this = this;


    if ( jQuery(e.target).parents('.del').length || jQuery(e.target).is('.del') ){

      Ext.Msg.confirm('您确认删除该收藏吗？','',function(confirmed){
        if( confirmed == 'yes' ){

          send_request( {
            api:'fav_job_del',
            method:'POST',
            params:{
              collectId:item_data.collectId
            },
            success:function(result, request){
              if( result.success ){
                switch( result.code ){
                  case 'SUCCESS':
                    //成功
                    console.log(result);
                    _this.update();
                    break;
                  case '1001':
                    //失败
                    break;
                  default:
                    toast("errCode:"+result.code);
                    break;
                }
              }else{

              }
            },
            fail:function(result){
              toast("您的网络似乎有点问题，请稍候再试！");
            },
            text:'加载中',
            silent:false,
            trigger:_this,
            check_login:true
          } );

        }
      });








    }else{
      change_page('InternPositionDetail',dataview,{positionId:item_data.posId});
    }


  },

  initialize: function() {
    this.callParent();
  },

  update: function(_p) {
    var _this = this;


    //if( _p && _p.keywords ){

      send_request( {
        api:'fav_job_list',
        method:'POST',
        params:{
          pageSize:100
        },
        success:function(result, request){
          if( result.success ){
            switch( result.code ){
              case '0000':
                //成功
                console.log(result);
                _this.build_list(result.data);
                break;
              case '1001':
                //失败
                break;
              default:
                toast("errCode:"+result.code);
                break;
            }
          }else{

          }
        },
        fail:function(result){
          toast("您的网络似乎有点问题，请稍候再试！");
        },
        text:'加载中',
        silent:false,
        trigger:_this,
        check_login:true
      } );

    //}



  },

  build_list: function(data) {

    var _this = this;
    var x$nodata = i$('nodata',_this);

    var x$list = x$('list_uc_fav_job');



    //x$list.removeAll();


    if(data && data.length){


      for( var i=0;i<data.length;i++ ){
        var date_ra = parse_date(data[i].collectTime,'date_');
        jQuery.extend( data[i],date_ra );
      }


      set_store_data(x$list,data);


      x$list.show();
      x$nodata.hide();



    }else{
      set_store_data(x$list,[]);


      x$list.hide();
      x$nodata.show();
    }


    refresh_scroll(x$list);
  }

});