/*
 * File: app/view/Login.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.view.Login', {
  extend: 'Ext.Container',
  alias: 'widget.login',

  requires: [
    'Ext.TitleBar',
    'Ext.Button',
    'Ext.form.Panel',
    'Ext.form.FieldSet',
    'Ext.field.Password'
  ],

  config: {
    cls: 'zjs',
    id: 'page_login',
    layout: 'card',
    items: [
      {
        xtype: 'titlebar',
        cls: 'zjs-bg-green',
        docked: 'top',
        ui: 'zjs',
        title: '用户登录',
        items: [
          {
            xtype: 'button',
            height: 30,
            itemId: 'mybutton23',
            ui: 'plain',
            width: 30,
            icon: '',
            iconCls: 'zjs-icon-back',
            text: 'back'
          },
          {
            xtype: 'button',
            align: 'right',
            itemId: 'mybutton24',
            text: '注册'
          }
        ]
      },
      {
        xtype: 'formpanel',
        scrollable: 'vertical',
        items: [
          {
            xtype: 'fieldset',
            title: '',
            items: [
              {
                xtype: 'textfield',
                id: 'login.fe_username',
                label: '账户',
                name: 'login.fe_username',
                required: true
              },
              {
                xtype: 'passwordfield',
                id: 'login.fe_password',
                label: '密码',
                name: 'login.fe_password',
                required: true
              }
            ]
          },
          {
            xtype: 'button',
            itemId: 'mybutton7',
            margin: '0 0.5em',
            ui: 'confirm',
            text: '登录'
          },
          {
            xtype: 'button',
            itemId: 'mybutton8',
            margin: '10px 0.5em 0',
            ui: 'action',
            text: '忘记密码'
          }
        ]
      }
    ],
    listeners: [
      {
        fn: 'onMybutton23Tap',
        event: 'tap',
        delegate: '#mybutton23'
      },
      {
        fn: 'onMybutton24Tap',
        event: 'tap',
        delegate: '#mybutton24'
      },
      {
        fn: 'onMybutton7Tap',
        event: 'tap',
        delegate: '#mybutton7'
      },
      {
        fn: 'onMybutton8Tap',
        event: 'tap',
        delegate: '#mybutton8'
      }
    ]
  },

  onMybutton23Tap: function(button, e, eOpts) {


    if( CURRENT_TAB && CURRENT_NAV ){
      var cur_tab_id = CURRENT_TAB.id;
      var cur_nav_length = CURRENT_NAV.getItems().length;
      var cur_page = CURRENT_NAV.getActiveItem();
      var is_login = cur_page.xtype == 'login';

      //console.log('CUR PAGE');
      //console.log(cur_page);
      //console.log(cur_page.xtype);

      switch( cur_tab_id ){
        case 'tab_home':
          if( cur_nav_length > 2 ){
            CURRENT_NAV.pop(2);
            //toast('APP POP');
          }else{
            //toast('APP KILL');
          }
          break;
        case 'tab_user':
          go_home();
          break;
        case 'tab_msg':
          go_home();
          break;
        case 'tab_more':
          if( cur_nav_length > 2 ){
            CURRENT_NAV.pop();
            //toast('APP POP');
          }else{
            //toast('APP HOME');
            go_home();
          }
          break;
      }
    }else{
      //exapp;
      //toast('APP EXIT');
    }



    /*
    //button.up('navigationview').pop();

    var nav_view = button.up('navigationview');

    var cur_active_item = Ext.Viewport.getActiveItem();
    var cur_active_item_nav_view = cur_active_item.up('navigationview');


    //console.log(nav_view);
    //console.log(nav_view.pop);
    var items = nav_view.getItems();
    console.log(items);

    if( nav_view && nav_view.pop ){
      console.log(nav_view.getItems().length);
      if( nav_view.getItems().length <=3 ){
        go_home();
      }else{
        nav_view.pop();
      }

    }else{
      go_home();
    }
    */
  },

  onMybutton24Tap: function(button, e, eOpts) {
    change_page('Register',button);
  },

  onMybutton7Tap: function(button, e, eOpts) {
    var fe_username = x$('login.fe_username');
    var fe_password = x$('login.fe_password');


    var username_val = fe_username.getValue();
    var password_val = fe_password.getValue();

    if(_G.DEBUG){
      username_val = username_val || 'zhaozuowen987469@126.com';
      password_val = password_val || '123456';
    }


    if( username_val && password_val ){

      send_request( {
        api:'login',
        method:'POST',
        params:{
          userName:username_val,
          password:password_val
        },
        success:function(result, request){
          if( result.success ){
            switch( result.code ){
              case '0000':
                //成功
                toast("登录成功。欢迎回来！");
                set_s('token',result.token);
                //reload_app();
                go_home();
                break;
              case '1001':
                //失败
                toast("登录失败，请输入正确的用户名和密码");
                break;
              default:
                toast("errCode:"+result.code);
                break;
            }
          }else{

          }
        },
        fail:function(result){
          toast("您的网络似乎有点问题，请稍候再试！");
        },
        text:'加载中',
        silent:false,
        trigger:button,
        check_login:false
      } );

    }else{
      toast("请输入用户名和密码。");
    }


    //Ext.Msg.alert("恭喜您，登录成功！");
    //button.up('navigationview').pop();
  },

  onMybutton8Tap: function(button, e, eOpts) {
    change_page('ResetPassword',button);
  }

});