/*
 * File: app/view/More.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.view.More', {
  extend: 'Ext.Container',
  alias: 'widget.more',

  requires: [
    'Ext.TitleBar',
    'Ext.dataview.DataView',
    'Ext.XTemplate'
  ],

  config: {
    cls: 'zjs',
    layout: 'fit',
    items: [
      {
        xtype: 'titlebar',
        cls: 'zjs-bg-green',
        docked: 'top',
        ui: 'zjs',
        title: '更多'
      },
      {
        xtype: 'dataview',
        cls: 'zjs-listview-1line',
        itemId: 'menu_list',
        minHeight: 180,
        scrollable: 'vertical',
        disableSelection: true,
        itemTpl: [
          '<div class="li">',
          '  <div class="c">',
          '    <h4>{title}</h4>',
          '  </div>',
          '  <div class="i">',
          '    <span></span>',
          '  </div>',
          '</div>'
        ]
      }
    ],
    listeners: [
      {
        fn: 'onMydataview2ItemTap',
        event: 'itemtap',
        delegate: '#menu_list'
      }
    ]
  },

  onMydataview2ItemTap: function(dataview, index, target, record, e, eOpts) {

    var item_data = record.data;


    switch( item_data.action ){

      case 'push_setting':
        change_page('PushSettings',dataview);
        break;
      case 'account_bind':
        if( is_login() ){
          change_page('AccountBind',dataview);
        }else{
          show_login(dataview);
          toast('您需要先登录才能绑定账号。');
        }
        break;
      case 'feedback':
        if( is_login() ){
          change_page('Feedback',dataview);
        }else{
          show_login(dataview);
          toast('您需要先登录才能留言。');
        }
        break;
      case 'clear_cache':

        Ext.Msg.confirm('确认清除缓存','您确定要清除缓存吗？',function(result){
          if( result == 'yes' ){
            clear_data();
            go_home();
            Ext.Msg.alert('缓存清除成功！您将返回首页。');
          }
        });


        break;
      case 'check_update':

        check_new_version(function(result,success){
          if(success){
            if(result){
              Ext.Msg.confirm('版本更新','发现新的版本，您需要更新吗？',function(confirmed){
                if( confirmed == 'yes' ){
                  window.open(result, '_system');
                }
              });
            }else{
              toast('您已经是最新的版本。');
            }

          }else{
            toast('获取版本信息失败，请稍候再试。');
          }

        },false);

        break;
      case 'app_introduction':
        change_page('AppIntroduction',dataview);
        break;
      case 'account_quit':

        if( is_login()){
          Ext.Msg.confirm('确认退出','您确定要退出当前账号吗？',function(result){
            if( result == 'yes' ){
              logout(function(){
                toast('您已成功退出！');
                go_home();
              },function(){
                toast('退出登录失败，请稍候再试。');
              });
            }
          });
        }else{
          toast('您尚未登录。');
        }
        break;
      case 'app_config':
        change_page('AppConfig',dataview);
        break;
    }


    /*


    [{
        title: "推送设置",
        action: "push_setting"
    }, {
        title: "账号绑定",
        action: "account_bind"
    }, {
        title: "意见反馈",
        action: "feedback"
    }, {
        title: "清除缓存",
        action: "clear_cache"
    }, {
        title: "检查更新",
        action: "check_update"
    }, {
        title: "APP介绍",
        action: "app_introduction"
    }, {
        title: "退出当前账号",
        action: "account_quit"
    }]


    */
  },

  update: function(_p) {
    var _this = this

    var menu_data = [{
        title: "推送设置",
        action: "push_setting"
    }, {
        title: "账号绑定",
        action: "account_bind"
    }, {
        title: "意见反馈",
        action: "feedback"
    }, {
        title: "清除缓存",
        action: "clear_cache"
    }, {
        title: "检查更新",
        action: "check_update"
    }, {
        title: "APP介绍",
        action: "app_introduction"
    }/*, {
        title: "App Config",
        action: "app_config"
    }*/

    ];


    if( is_login() ){
      menu_data.push({
        title: "退出当前账号",
        action: "account_quit"
      });
    }




    var x$nav_list = _this.down('#menu_list');

    set_store_data(x$nav_list,menu_data);
  }

});