/*
 * File: app/view/MyNotice.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.view.MyNotice', {
  extend: 'Ext.Container',

  requires: [
    'Ext.TitleBar',
    'Ext.Button',
    'Ext.dataview.DataView',
    'Ext.XTemplate'
  ],

  config: {
    cls: 'zjs',
    layout: 'fit',
    items: [
      {
        xtype: 'titlebar',
        cls: 'zjs-bg-green',
        docked: 'top',
        ui: 'zjs',
        title: '我的提醒',
        items: [
          {
            xtype: 'button',
            height: 30,
            itemId: 'mybutton23',
            ui: 'plain',
            width: 30,
            icon: '',
            iconCls: 'zjs-icon-back',
            text: 'back'
          }
        ]
      },
      {
        xtype: 'dataview',
        cls: 'zjs-listview-calender',
        id: 'list-msg-remider',
        itemId: 'mydataview3',
        minHeight: 180,
        scrollable: 'vertical',
        disableSelection: true,
        itemTpl: [
          '<div class="li">',
          '	<div class="calendar">',
          '    <div class="date">{date_month}-{date_date}</div>',
          '    <div class="time">{date_am} {date_hour}:{date_minute}</div>',
          '    <div class="day">{date_localday}</div>',
          '  </div>',
          '  <div class="c">',
          '  	<h4>{remindTitle}</h4>',
          '    <p>地点：{remindAddress}</p>',
          '  </div>',
          '  <div class="i">',
          '  	<span></span>',
          '  </div>',
          '</div>'
        ]
      }
    ],
    listeners: [
      {
        fn: 'onMybutton23Tap',
        event: 'tap',
        delegate: '#mybutton23'
      },
      {
        fn: 'onMydataview2ItemTap1',
        event: 'itemtap',
        delegate: '#list-msg-remider'
      }
    ]
  },

  onMybutton23Tap: function(button, e, eOpts) {
    button.up('navigationview').pop();
  },

  onMydataview2ItemTap1: function(dataview, index, target, record, e, eOpts) {
    var item_data = record.data;

    var id = item_data.bizId;

    switch(item_data.bizType){
      case 0:
        change_page('CampusTalkDetail',dataview,{id:id});
        break;
      case 1:
        change_page('RecruitmentDetail',dataview,{id:id});
        break;
    }



  },

  initialize: function() {
    this.callParent();
  },

  update: function(_p) {
    var _this = this;


    send_request( {
      api:'msg.remider.list',
      method:'POST',
      params:{
        pageSize:100
      },
      success:function(result, request){
        if( result.success ){
          switch( result.code ){
            case '0000':
              //成功
              console.log(result);
              _this.build_list(result.data);
              break;
            case '1001':
              //失败
              break;
            default:
              toast("errCode:"+result.code);
              break;
          }
        }else{

        }
      },
      fail:function(result){
        toast("您的网络似乎有点问题，请稍候再试！");
      },
      text:'加载中',
      silent:false,
      trigger:_this,
      check_login:true
    } );


  },

  build_list: function(data) {
    var x$list = x$('list-msg-remider');


    console.log(data);

    if(data && data.length){

      for( var i=0;i<data.length;i++ ){
        var date_ra = parse_date(data[i].remindTime,'date_');
        jQuery.extend( data[i],date_ra );
      }


      x$list.removeCls('zj-list-no-data');
      x$list.setData(data);
    }else{
      x$list.addCls('zj-list-no-data');
      x$list.removeAll();
    }


    refresh_scroll(x$list);
  }

});