/*
 * File: app/view/NavTab5.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.view.NavTab5', {
  extend: 'Ext.navigation.View',
  alias: 'widget.navtab5',

  requires: [
    'Ext.navigation.Bar'
  ],

  config: {
    id: 'NavTab5',
    layout: {
      type: 'card',
      animation: false
    },
    navigationBar: {
      cls: 'zjs-bg-green',
      disabled: false,
      hidden: true,
      ui: 'zjs',
      hideOnMaskTap: false
    }
  }

});