/*
 * File: app/view/PG_Message.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.view.PG_Message', {
  extend: 'Ext.Container',
  alias: 'widget.pg_message',

  requires: [
    'Ext.TitleBar',
    'Ext.dataview.DataView',
    'Ext.XTemplate'
  ],

  config: {
    layout: 'fit',
    items: [
      {
        xtype: 'titlebar',
        cls: 'zjs-bg-green',
        docked: 'top',
        hidden: false,
        ui: 'zjs',
        title: '消息'
      },
      {
        xtype: 'dataview',
        cls: 'zjs-listview-1line',
        data: [
          {
            title: '我的提醒',
            badge: '',
            action: 'my_notice'
          },
          {
            title: '职位订阅',
            badge: '',
            action: 'job_book'
          },
          {
            title: '面试通知',
            badge: '',
            action: 'interview'
          }
        ],
        id: 'pg_message_list',
        itemId: 'mydataview15',
        disableSelection: true,
        itemTpl: [
          '<div class="li">',
          '  <div class="c">',
          '    <h4>{title}</h4>',
          '  </div>',
          '  <div class="i">',
          '    <span></span>',
          '  </div>',
          '  <tpl if="badge &gt; 0">',
          '  <div class="b">',
          '    <span>{badge}</span>',
          '  </div>',
          '  </tpl>',
          '</div>'
        ]
      }
    ],
    listeners: [
      {
        fn: 'onPg_message_listItemTap',
        event: 'itemtap',
        delegate: '#pg_message_list'
      }
    ]
  },

  onPg_message_listItemTap: function(dataview, index, target, record, e, eOpts) {

    var item_data = record.data;


    switch( item_data.action ){
      case 'my_notice':
        change_page('MyNotice',dataview);
        break;
      case 'job_book':
        change_page('JobBookList',dataview);
        break;
      case 'interview':
        change_page('InterviewNotice',dataview);
        break;
      case 'reply':
        change_page('TopicReply',dataview);
        break;
    }

  },

  update: function(_p) {
    var _this = this;


    send_request( {
      api:'msg.pull',
      method:'POST',
      params:{
        pageSize:100
      },
      success:function(result, request){
        if( result.success ){
          switch( result.code ){
            case '0000':
              //成功
              console.log(result);

              _this.build_list(result.data);
              break;
            case '1001':
              //失败
              break;
            default:
              toast("errCode:"+result.code);
              break;
          }
        }else{

        }
      },
      fail:function(result){
        toast("您的网络似乎有点问题，请稍候再试！");
      },
      text:'加载中',
      silent:false,
      trigger:_this,
      check_login:true
    } );


  },

  build_list: function(data) {

    var x$list = x$('pg_message_list');

    var nav_data = x$list.getData();


    if(data){

      nav_data[0].badge = ''+data.REMIND;
      nav_data[1].badge = ''+data.POSITION;
      nav_data[2].badge = ''+data.AUDITION;

    }

    set_store_data(x$list,nav_data);
    x$list.refresh();
    refresh_scroll(x$list);
  }

});