/*
 * File: app/view/PositionSubscribeByCompany.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.view.PositionSubscribeByCompany', {
  extend: 'Ext.Container',
  alias: 'widget.positionsubscribebycompany',

  requires: [
    'Ext.Panel',
    'Ext.field.Text',
    'Ext.Button',
    'Ext.Label',
    'Ext.dataview.DataView',
    'Ext.XTemplate'
  ],

  config: {
    layout: 'fit',
    items: [
      {
        xtype: 'panel',
        scrollable: 'vertical',
        items: [
          {
            xtype: 'panel',
            height: 200,
            items: [
              {
                xtype: 'textfield',
                id: 'pos_sub_by_co_kw',
                placeHolder: '请输入企业名称或关键字'
              },
              {
                xtype: 'button',
                id: 'pos_sub_by_co_btn_sub',
                itemId: 'mybutton79',
                margin: '10px',
                ui: 'confirm',
                text: '订 阅'
              },
              {
                xtype: 'label',
                cls: 'detail_content content_con',
                html: '  热门企业：百度 腾讯  阿里巴巴 奇虎360  新浪网  网易  搜狐 ',
                margin: '10px'
              },
              {
                xtype: 'label',
                cls: 'detail_content content_con',
                html: '<h4>当前的订阅</h4>',
                margin: '20px 10px 0'
              }
            ]
          },
          {
            xtype: 'dataview',
            cls: 'zjs-listview-booked-position',
            hidden: false,
            id: 'pos_sub_by_co_list_sub',
            itemId: 'mydataview6',
            scrollable: false,
            disableSelection: true,
            itemTpl: [
              '<div class="li">',
              '  <div class="icon">',
              '  	<span></span>',
              '    已订阅',
              '  </div>',
              '  <div class="c">',
              '    <div class="cw">',
              '    	{searchName}',
              '    </div>',
              '  </div>',
              '  <div class="i i_delete"> <span></span> </div>',
              '</div>',
              '',
              '',
              ''
            ]
          }
        ]
      }
    ],
    listeners: [
      {
        fn: 'onPos_sub_by_pos_btn_subTap',
        event: 'tap',
        delegate: '#pos_sub_by_co_btn_sub'
      },
      {
        fn: 'onMydataview5ItemTap1',
        event: 'itemtap',
        delegate: '#pos_sub_by_co_list_sub'
      }
    ]
  },

  onPos_sub_by_pos_btn_subTap: function(button, e, eOpts) {
    var _this = this;


    var $kw = x$('pos_sub_by_co_kw');



    var params = {
      subscriptionType:1
    };

    var have_param = false;

    var value = $kw.getValue();
    if( value === '' ){
    }else{
      params.companyKey = fix_cn(value);
      have_param = true;

    console.log(params);


    }


    console.log(params);

    if( have_param ){
      send_request( {
        api:'sub_add',
        method:'POST',
        params:params,
        success:function(result, request){
          if( result.success ){
            switch( result.code ){
              case '0000':
                //成功
                toast('恭喜您，您已订阅成功。');
                _this.update_list();
                _this.reset();
                break;
              case '1001':
                //失败
                break;
              default:
                toast("errCode:"+result.code);
                break;
            }
          }else{

          }
        },
        fail:function(result){
          toast("您的网络似乎有点问题，请稍候再试！");
        },
        text:'加载中',
        silent:false,
        trigger:button,
        check_login:false
      } );


    }else{
      toast('请输入您想订阅的企业。');
    }





  },

  onMydataview5ItemTap1: function(dataview, index, target, record, e, eOpts) {
    var _this = this;


    if( event_on(e,'.i_delete') ){

      Ext.Msg.confirm("删除确认","您确认删除这条订阅吗？",function(result){
        if( result=='yes' ){
          send_request( {
            api:'sub_del',
            method:'POST',
            params:{
              subscriptionId:record.data.subscriptionId
            },
            success:function(result, request){
              if( result.success ){
                switch( result.code ){
                  case '0000':
                    //成功
                    //console.log(result);
                    toast("订阅删除成功。");
                    _this.update_list();
                    break;
                  case '1001':
                    //失败
                    break;
                  default:
                    toast("errCode:"+result.code);
                    break;
                }
              }else{

              }
            },
            fail:function(result){
              toast("您的网络似乎有点问题，请稍候再试！");
            },
            text:'加载中',
            silent:false,
            trigger:dataview,
            check_login:false
          } );

        }
      });

    }
  },

  update_list: function(_p) {
    var $list = x$('pos_sub_by_co_list_sub');


    var _this = this;

    send_request( {
      api:'msg.job_subscribe.list',
      method:'POST',
      params:{
        pageSize:100,
        subscriptionType:1
      },
      success:function(result, request){
        if( result.success ){
          switch( result.code ){
            case '0000':
              //成功
              set_store_data( $list,result.data );
              $list.setHeight(result.data.length*59);
              break;
            case '1001':
              //失败
              break;
            default:
              toast("errCode:"+result.code);
              break;
          }
        }else{

        }
      },
      fail:function(result){
        toast("您的网络似乎有点问题，请稍候再试！");
      },
      text:'加载中',
      silent:false,
      trigger:_this,
      check_login:false,
      group:'p_s_b_p'
    } );



  },

  initialize: function() {
    this.callParent();

    this.update_list();
  }

});