/*
 * File: app/view/PositionSubscribeByPosition.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.view.PositionSubscribeByPosition', {
  extend: 'Ext.Container',
  alias: 'widget.positionsubscribebyposition',

  requires: [
    'Ext.form.Panel',
    'Ext.form.FieldSet',
    'Ext.field.Text',
    'Ext.SegmentedButton',
    'Ext.Button',
    'Ext.Label',
    'Ext.XTemplate',
    'Ext.TitleBar',
    'Ext.dataview.List'
  ],

  config: {
    layout: 'fit',
    items: [
      {
        xtype: 'panel',
        hidden: false,
        id: 'p_s_b_p_scp',
        scrollable: 'vertical',
        items: [
          {
            xtype: 'formpanel',
            height: 370,
            hidden: false,
            scrollable: false,
            items: [
              {
                xtype: 'container',
                html: '<h4>请选择筛选条件</h4>',
                margin: '10px'
              },
              {
                xtype: 'fieldset',
                hidden: false,
                items: [
                  {
                    xtype: 'textfield',
                    id: 'pos_sub_by_pos_fe_area_CNL',
                    itemId: 'myselectfield3',
                    label: '地区',
                    placeHolder: '不限',
                    readOnly: true
                  },
                  {
                    xtype: 'textfield',
                    id: 'pos_sub_by_pos_fe_industry_CNL',
                    itemId: 'myselectfield1',
                    label: '行业',
                    placeHolder: '不限',
                    readOnly: true
                  },
                  {
                    xtype: 'textfield',
                    id: 'pos_sub_by_pos_fe_func_CNL',
                    itemId: 'myselectfield2',
                    label: '职能',
                    placeHolder: '不限',
                    readOnly: true
                  },
                  {
                    xtype: 'textfield',
                    id: 'pos_sub_by_pos_fe_salary_CNL',
                    label: '薪资',
                    placeHolder: '不限',
                    readOnly: true
                  },
                  {
                    xtype: 'textfield',
                    id: 'pos_sub_by_pos_fe_type_CNL',
                    label: '工作性质',
                    placeHolder: '不限',
                    readOnly: true
                  },
                  {
                    xtype: 'textfield',
                    id: 'pos_sub_by_pos_fe_kw',
                    label: '关键词',
                    placeHolder: '选填'
                  }
                ]
              }
            ]
          },
          {
            xtype: 'segmentedbutton',
            cls: 'zjs-segment-btn-bottom',
            height: 50,
            hidden: false,
            defaults: {
              flex: 1
            },
            items: [
              {
                xtype: 'button',
                flex: 3,
                cls: 'btn-green',
                itemId: 'mybutton72',
                iconCls: 'zjs-icon-add',
                text: '订阅'
              },
              {
                xtype: 'button',
                cls: 'btn-blue',
                itemId: 'mybutton73',
                text: '重新设置'
              }
            ]
          },
          {
            xtype: 'panel',
            hidden: false,
            items: [
              {
                xtype: 'label',
                cls: 'detail_content content_con',
                html: '<h4>当前的订阅</h4>',
                margin: '20px 10px 0'
              },
              {
                xtype: 'dataview',
                cls: 'zjs-listview-booked-position',
                hidden: false,
                id: 'pos_sub_by_pos_list_sub',
                itemId: 'pos_sub_by_pos_list_sub',
                scrollable: false,
                disableSelection: true,
                itemTpl: [
                  '<div class="li">',
                  '  <div class="icon">',
                  '  	<span></span>',
                  '    已订阅',
                  '  </div>',
                  '  <div class="c">',
                  '    <div class="cw">',
                  '    	{searchName}',
                  '    </div>',
                  '  </div>',
                  '  <div class="i i_delete"> <span></span> </div>',
                  '</div>'
                ]
              }
            ]
          }
        ]
      },
      {
        xtype: 'container',
        centered: true,
        height: 250,
        hidden: true,
        itemId: 'cnl_pop_area',
        width: 280,
        layout: 'fit',
        modal: true,
        items: [
          {
            xtype: 'titlebar',
            docked: 'top',
            title: '地区',
            items: [
              {
                xtype: 'button',
                itemId: 'cnl_pop_back_area',
                text: '返回'
              },
              {
                xtype: 'button',
                align: 'right',
                itemId: 'cnl_pop_cancel_area',
                text: '重置'
              }
            ]
          },
          {
            xtype: 'list',
            itemId: 'cnl_area',
            disableSelection: true,
            itemCls: 'leaf_list',
            itemTpl: [
              '<div class="{__leaf_cls}">{areaName}</div>'
            ]
          }
        ]
      },
      {
        xtype: 'container',
        centered: true,
        height: 250,
        hidden: true,
        itemId: 'cnl_pop_industry',
        width: 280,
        layout: 'fit',
        modal: true,
        items: [
          {
            xtype: 'titlebar',
            docked: 'top',
            title: '行业',
            items: [
              {
                xtype: 'button',
                itemId: 'cnl_pop_back_industry',
                text: '返回'
              },
              {
                xtype: 'button',
                align: 'right',
                itemId: 'cnl_pop_cancel_industry',
                text: '重置'
              }
            ]
          },
          {
            xtype: 'list',
            itemId: 'cnl_industry',
            disableSelection: true,
            itemCls: 'leaf_list',
            itemTpl: [
              '<div class="{__leaf_cls}">{text}</div>'
            ]
          }
        ]
      },
      {
        xtype: 'container',
        centered: true,
        height: 250,
        hidden: true,
        itemId: 'cnl_pop_func',
        width: 280,
        layout: 'fit',
        modal: true,
        items: [
          {
            xtype: 'titlebar',
            docked: 'top',
            title: '职能',
            items: [
              {
                xtype: 'button',
                itemId: 'cnl_pop_back_func',
                text: '返回'
              },
              {
                xtype: 'button',
                align: 'right',
                itemId: 'cnl_pop_cancel_func',
                text: '重置'
              }
            ]
          },
          {
            xtype: 'list',
            itemId: 'cnl_func',
            disableSelection: true,
            itemCls: 'leaf_list',
            itemTpl: [
              '<div class="{__leaf_cls}">{text}</div>'
            ]
          }
        ]
      },
      {
        xtype: 'container',
        centered: true,
        height: 250,
        hidden: true,
        itemId: 'cnl_pop_salary',
        width: 280,
        layout: 'fit',
        modal: true,
        items: [
          {
            xtype: 'titlebar',
            docked: 'top',
            title: '薪资',
            items: [
              {
                xtype: 'button',
                itemId: 'cnl_pop_back_salary',
                text: '返回'
              },
              {
                xtype: 'button',
                align: 'right',
                itemId: 'cnl_pop_cancel_salary',
                text: '重置'
              }
            ]
          },
          {
            xtype: 'list',
            itemId: 'cnl_salary',
            disableSelection: true,
            itemCls: 'leaf_list',
            itemTpl: [
              '<div class="{__leaf_cls}">{salaryName}</div>'
            ]
          }
        ]
      },
      {
        xtype: 'container',
        centered: true,
        height: 250,
        hidden: true,
        itemId: 'cnl_pop_type',
        width: 280,
        layout: 'fit',
        modal: true,
        items: [
          {
            xtype: 'titlebar',
            docked: 'top',
            title: '工作性质',
            items: [
              {
                xtype: 'button',
                itemId: 'cnl_pop_back_type',
                text: '返回'
              },
              {
                xtype: 'button',
                align: 'right',
                itemId: 'cnl_pop_cancel_type',
                text: '重置'
              }
            ]
          },
          {
            xtype: 'list',
            itemId: 'cnl_type',
            disableSelection: true,
            itemCls: 'leaf_list',
            itemTpl: [
              '<div class="{__leaf_cls}">{name}</div>'
            ]
          }
        ]
      }
    ],
    listeners: [
      {
        fn: 'onMybutton72Tap1',
        event: 'tap',
        delegate: '#mybutton72'
      },
      {
        fn: 'onMybutton73Tap1',
        event: 'tap',
        delegate: '#mybutton73'
      },
      {
        fn: 'onPos_sub_by_pos_list_subItemTap',
        event: 'itemtap',
        delegate: '#pos_sub_by_pos_list_sub'
      },
      {
        fn: 'onMybutton23Tap311',
        event: 'tap',
        delegate: '#cnl_pop_back_area'
      },
      {
        fn: 'onMybutton14Tap',
        event: 'tap',
        delegate: '#cnl_pop_cancel_area'
      },
      {
        fn: 'onMybutton23Tap3111',
        event: 'tap',
        delegate: '#cnl_pop_back_industry'
      },
      {
        fn: 'onMybutton14Tap1',
        event: 'tap',
        delegate: '#cnl_pop_cancel_industry'
      },
      {
        fn: 'onMybutton23Tap31111',
        event: 'tap',
        delegate: '#cnl_pop_back_func'
      },
      {
        fn: 'onMybutton14Tap11',
        event: 'tap',
        delegate: '#cnl_pop_cancel_func'
      },
      {
        fn: 'onMybutton23Tap311111',
        event: 'tap',
        delegate: '#cnl_pop_back_salary'
      },
      {
        fn: 'onMybutton14Tap111',
        event: 'tap',
        delegate: '#cnl_pop_cancel_salary'
      },
      {
        fn: 'onMybutton23Tap3111111',
        event: 'tap',
        delegate: '#cnl_pop_back_type'
      },
      {
        fn: 'onMybutton14Tap1111',
        event: 'tap',
        delegate: '#cnl_pop_cancel_type'
      }
    ]
  },

  onMybutton72Tap1: function(button, e, eOpts) {
    var _this = this;


    var $area = x$('pos_sub_by_pos_fe_area_CNL');
    var $industry = x$('pos_sub_by_pos_fe_industry_CNL');
    var $func = x$('pos_sub_by_pos_fe_func_CNL');
    var $salary = x$('pos_sub_by_pos_fe_salary_CNL');
    var $type = x$('pos_sub_by_pos_fe_type_CNL');
    var $kw = x$('pos_sub_by_pos_fe_kw');



    var params = {
      subscriptionType:0
    };

    var have_param = false;

    var value = $area.field_val || '';
    if( value === '' ){
    }else{
      params.areaId=value;
      have_param = true;
    }

    var value = $industry.field_val || '';
    if( value ){
      params.industryId=value;
      have_param = true;
    }

    var value = $func.field_val || '';
    if( value ){
      params.functionId=value;
      have_param = true;
    }

    var value = $salary.field_val || '';
    if( value === '' ){
    }else{
      params.salaryId=value;
      have_param = true;
    }

    var value = $type.field_val || '';
    if( value === '' ){
    }else{
      params.positionType=value;
      have_param = true;
    }

    var value = $kw.getValue();
    if( value === '' ){
    }else{
      params.positionKey = fix_cn(value);
      params.companyKey = fix_cn(value);
      have_param = true;
    }


    if( have_param ){
      send_request( {
        api:'sub_add',
        method:'POST',
        params:params,
        success:function(result, request){
          if( result.success ){
            switch( result.code ){
              case '0000':
                //成功
                toast('恭喜您，您已订阅成功。');
                _this.reset();
                _this.update_list();
                break;
              case '1001':
                //失败
                break;
              default:
                toast("errCode:"+result.code);
                break;
            }
          }else{

          }
        },
        fail:function(result){
          toast("您的网络似乎有点问题，请稍候再试！");
        },
        text:'加载中',
        silent:false,
        trigger:button,
        check_login:false
      } );


    }else{
      toast('请选择筛选条件。');
    }





  },

  onMybutton73Tap1: function(button, e, eOpts) {
    this.reset();
  },

  onPos_sub_by_pos_list_subItemTap: function(dataview, index, target, record, e, eOpts) {
    var _this = this;


    if( event_on(e,'.i_delete') ){

      Ext.Msg.confirm("删除确认","您确认删除这条订阅吗？",function(result){
        if( result=='yes' ){
          send_request( {
            api:'sub_del',
            method:'POST',
            params:{
              subscriptionId:record.data.subscriptionId
            },
            success:function(result, request){
              if( result.success ){
                switch( result.code ){
                  case '0000':
                    //成功
                    //console.log(result);
                    toast("订阅删除成功。");
                    _this.update_list();
                    break;
                  case '1001':
                    //失败
                    break;
                  default:
                    toast("errCode:"+result.code);
                    break;
                }
              }else{

              }
            },
            fail:function(result){
              toast("您的网络似乎有点问题，请稍候再试！");
            },
            text:'加载中',
            silent:false,
            trigger:dataview,
            check_login:false
          } );

        }
      });

    }
  },

  onMybutton23Tap311: function(button, e, eOpts) {
    var _this = this;

    if( !_this.CNL_area.pop() ){
      window.setTimeout(function(){
        _this.down('#cnl_pop_area').hide();
      },520);
    }

  },

  onMybutton14Tap: function(button, e, eOpts) {
    var _this = this;

    var x$input = x$('pos_sub_by_pos_fe_area_CNL');

    x$input.setValue('');
    x$input.field_val = '';

    window.setTimeout(function(){
      _this.down('#cnl_pop_area').hide();
    },520);
  },

  onMybutton23Tap3111: function(button, e, eOpts) {
    var _this = this;

    if( !_this.CNL_industry.pop() ){
      window.setTimeout(function(){
        _this.down('#cnl_pop_industry').hide();
      },520);
    }

  },

  onMybutton14Tap1: function(button, e, eOpts) {
    var _this = this;

    var x$input = x$('pos_sub_by_pos_fe_industry_CNL');

    x$input.setValue('');
    x$input.field_val = '';

    window.setTimeout(function(){
      _this.down('#cnl_pop_industry').hide();
    },520);
  },

  onMybutton23Tap31111: function(button, e, eOpts) {
    var _this = this;

    if( !_this.CNL_func.pop() ){
      window.setTimeout(function(){
        _this.down('#cnl_pop_func').hide();
      },520);
    }

  },

  onMybutton14Tap11: function(button, e, eOpts) {
    var _this = this;

    var x$input = x$('pos_sub_by_pos_fe_func_CNL');

    x$input.setValue('');
    x$input.field_val = '';

    window.setTimeout(function(){
      _this.down('#cnl_pop_func').hide();
    },520);
  },

  onMybutton23Tap311111: function(button, e, eOpts) {
    var _this = this;

    if( !_this.CNL_salary.pop() ){
      window.setTimeout(function(){
        _this.down('#cnl_pop_salary').hide();
      },520);
    }

  },

  onMybutton14Tap111: function(button, e, eOpts) {
    var _this = this;

    var x$input = x$('pos_sub_by_pos_fe_salary_CNL');

    x$input.setValue('');
    x$input.field_val = '';

    window.setTimeout(function(){
      _this.down('#cnl_pop_salary').hide();
    },520);
  },

  onMybutton23Tap3111111: function(button, e, eOpts) {
    var _this = this;

    if( !_this.CNL_type.pop() ){
      window.setTimeout(function(){
        _this.down('#cnl_pop_type').hide();
      },520);
    }

  },

  onMybutton14Tap1111: function(button, e, eOpts) {
    var _this = this;

    var x$input = x$('pos_sub_by_pos_fe_type_CNL');

    x$input.setValue('');
    x$input.field_val = '';

    window.setTimeout(function(){
      _this.down('#cnl_pop_type').hide();
    },520);
  },

  update: function(_p) {

    var _this = this;


    send_request( {
      api:'enum',
      method:'POST',
      params:{
        pageSize:100
      },
      success:function(result, request){
        if( result.success ){
          switch( result.code ){
            case '0000':
              //成功
              _this.init_enum(result.data);
              _this.reset();
              break;
            case '1001':
              //失败
              break;
            default:
              toast("errCode:"+result.code);
              break;
          }
        }else{

        }
      },
      fail:function(result){
        toast("您的网络似乎有点问题，请稍候再试！");
      },
      text:'加载中',
      silent:false,
      trigger:_this,
      check_login:false,
      group:'p_s_b_p'
    } );




    send_request( {
      api:'area_list',
      method:'POST',
      params:{
        pageSize:100,
        parentId:_G._cityId
      },
      success:function(result, request){
        if( result.success ){
          switch( result.code ){
            case '0000':
              //成功
              _this.init_area(result.data);
              _this.reset();
              break;
            case '1001':
              //失败
              break;
            default:
              toast("errCode:"+result.code);
              break;
          }
        }else{

        }
      },
      fail:function(result){
        toast("您的网络似乎有点问题，请稍候再试！");
      },
      text:'加载中',
      silent:false,
      trigger:_this,
      check_login:false,
      group:'p_s_b_p'
    } );






    send_request( {
      api:'opt_salary',
      method:'POST',
      params:{
        pageSize:100,
        parentId:_G._cityId
      },
      success:function(result, request){
        if( result.success ){
          switch( result.code ){
            case '0000':
              //成功
              _this.init_salary(result.data);
              _this.reset();
              break;
            case '1001':
              //失败
              break;
            default:
              toast("errCode:"+result.code);
              break;
          }
        }else{

        }
      },
      fail:function(result){
        toast("您的网络似乎有点问题，请稍候再试！");
      },
      text:'加载中',
      silent:false,
      trigger:_this,
      check_login:false,
      group:'p_s_b_p'
    } );




    send_request( {
      api:'opt_industry',
      method:'POST',
      params:{
        pageSize:100,
        parentId:_G._cityId
      },
      success:function(result, request){
        if( result.success ){
          switch( result.code ){
            case '0000':
              //成功
              _this.init_industry(result.data);
              _this.reset();
              break;
            case '1001':
              //失败
              break;
            default:
              toast("errCode:"+result.code);
              break;
          }
        }else{

        }
      },
      fail:function(result){
        toast("您的网络似乎有点问题，请稍候再试！");
      },
      text:'加载中',
      silent:false,
      trigger:_this,
      check_login:false,
      group:'p_s_b_p'
    } );



    send_request( {
      api:'opt_functions',
      method:'POST',
      params:{
        pageSize:100,
        parentId:_G._cityId
      },
      success:function(result, request){
        if( result.success ){
          switch( result.code ){
            case '0000':
              //成功
              _this.init_func(result.data);
              _this.reset();
              break;
            case '1001':
              //失败
              break;
            default:
              toast("errCode:"+result.code);
              break;
          }
        }else{

        }
      },
      fail:function(result){
        toast("您的网络似乎有点问题，请稍候再试！");
      },
      text:'加载中',
      silent:false,
      trigger:_this,
      check_login:false,
      group:'p_s_b_p'
    } );




    this.update_list();
  },

  update_list: function(_p) {
    var $list = x$('pos_sub_by_pos_list_sub');



    var _this = this;

    send_request( {
      api:'msg.job_subscribe.list',
      method:'POST',
      params:{
        pageSize:100,
        subscriptionType:0
      },
      success:function(result, request){
        if( result.success ){
          switch( result.code ){
            case '0000':
              //成功
              //$list.hide();
              set_store_data( $list,result.data );
              $list.setHeight(result.data.length*59);

              refresh_scroll(x$('p_s_b_p_scp'));

              //$list.show();
              break;
            case '1001':
              //失败
              break;
            default:
              toast("errCode:"+result.code);
              break;
          }
        }else{

        }
      },
      fail:function(result){
        toast("您的网络似乎有点问题，请稍候再试！");
      },
      text:'加载中',
      silent:false,
      trigger:_this,
      check_login:true,
      group:'p_s_b_p'
    } );



  },

  init_enum: function(data) {
    var _this = this;


    var x$input = x$('pos_sub_by_pos_fe_type_CNL');
    var x$pop =  _this.down('#cnl_pop_type');
    var x$list = _this.down('#cnl_type');

    x$input.addListener('focus',function(){
      x$pop.show();
      _this.CNL_type.reset();
    });


    _this.CNL_type = new LD_Nested_List( x$list,data.positionType,'items',function(data){
      x$input.setValue(data.name);
      x$input.field_val = data.value;
      window.setTimeout(function(){
        x$pop.hide();
      },520);
    } );



  },

  init_area: function(data) {
    var _this = this;


    var x$input = x$('pos_sub_by_pos_fe_area_CNL');
    var x$pop =  _this.down('#cnl_pop_area');
    var x$list = _this.down('#cnl_area');

    x$input.addListener('focus',function(){
      x$pop.show();
      _this.CNL_area.reset();
    });


    _this.CNL_area = new LD_Nested_List( x$list,data,'items',function(data){
      x$input.setValue(data.areaName);
      x$input.field_val = data.areaId;
      window.setTimeout(function(){
        x$pop.hide();
      },520);
    } );



  },

  init_industry: function(data) {

    var _this = this;

    data = make_nested_data(data,0,'industryId','industryName');

    var x$input = x$('pos_sub_by_pos_fe_industry_CNL');
    var x$pop =  _this.down('#cnl_pop_industry');
    var x$list = _this.down('#cnl_industry');

    x$input.addListener('focus',function(){
      x$pop.show();
      _this.CNL_industry.reset();
    });


    _this.CNL_industry = new LD_Nested_List( x$list,data,'items',function(data){
      x$input.setValue(data.text);
      x$input.field_val = data.record.industryId;
      window.setTimeout(function(){
        x$pop.hide();
      },520);
    } );



  },

  init_func: function(data) {
    var _this = this;


    var data = make_nested_data(data,0,'functionId','functionName');

    var x$input = x$('pos_sub_by_pos_fe_func_CNL');
    var x$pop =  _this.down('#cnl_pop_func');
    var x$list = _this.down('#cnl_func');

    x$input.addListener('focus',function(){
      x$pop.show();
      _this.CNL_func.reset();
    });


    _this.CNL_func = new LD_Nested_List( x$list,data,'items',function(data){
      x$input.setValue(data.text);
      x$input.field_val = data.record.functionId;
      window.setTimeout(function(){
        x$pop.hide();
      },520);
    } );



  },

  init_salary: function(data) {
    var _this = this;

    var x$input = x$('pos_sub_by_pos_fe_salary_CNL');
    var x$pop =  _this.down('#cnl_pop_salary');
    var x$list = _this.down('#cnl_salary');

    x$input.addListener('focus',function(){
      x$pop.show();
      _this.CNL_salary.reset();
    });


    _this.CNL_salary = new LD_Nested_List( x$list,data,'items',function(data){
      x$input.setValue(data.salaryName);
      x$input.field_val = data.salaryId;
      window.setTimeout(function(){
        x$pop.hide();
      },520);
    } );



  },

  reset: function() {
    var $area = x$('pos_sub_by_pos_fe_area_CNL');
    var $industry = x$('pos_sub_by_pos_fe_industry_CNL');
    var $func = x$('pos_sub_by_pos_fe_func_CNL');
    var $salary = x$('pos_sub_by_pos_fe_salary_CNL');
    var $type = x$('pos_sub_by_pos_fe_type_CNL');
    var $kw = x$('pos_sub_by_pos_fe_kw');

    $area.setValue('');
    $area.field_val='';
    $industry.setValue('');
    $industry.field_val='';
    $func.setValue('');
    $func.field_val='';
    $salary.setValue('');
    $salary.field_val='';
    $type.setValue('');
    $type.field_val='';

    $kw.setValue('');
  }

});