/*
 * File: app/view/ShareFormSina.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.view.ShareFormSina', {
  extend: 'Ext.Container',

  requires: [
    'Ext.TitleBar',
    'Ext.Button',
    'Ext.form.Panel',
    'Ext.field.TextArea'
  ],

  config: {
    cls: 'zjs',
    layout: 'card',
    items: [
      {
        xtype: 'titlebar',
        cls: 'zjs-bg-green',
        docked: 'top',
        ui: 'zjs',
        title: '分享至新浪微博',
        items: [
          {
            xtype: 'button',
            height: 30,
            itemId: 'mybutton23',
            ui: 'plain',
            width: 30,
            icon: '',
            iconCls: 'zjs-icon-back',
            text: 'back'
          },
          {
            xtype: 'button',
            align: 'right',
            itemId: 'mybutton44',
            text: '发布'
          }
        ]
      },
      {
        xtype: 'formpanel',
        scrollable: 'vertical',
        items: [
          {
            xtype: 'textareafield',
            height: 150,
            id: 'ta_share_sina',
            placeHolder: ''
          }
        ]
      }
    ],
    listeners: [
      {
        fn: 'onMybutton23Tap',
        event: 'tap',
        delegate: '#mybutton23'
      },
      {
        fn: 'onMybutton44Tap',
        event: 'tap',
        delegate: '#mybutton44'
      }
    ]
  },

  onMybutton23Tap: function(button, e, eOpts) {
    button.up('navigationview').pop();
  },

  onMybutton44Tap: function(button, e, eOpts) {
    var _this = this;

    var x$ta = x$('ta_share_sina');

    var text = x$ta.getValue();


    console.log(_this.sns_data);
    console.log(_this.share_data);


    if(text){
      share_to_sina(_this.sns_data.access_token,text,function(){
        toast('您的分享已发送。');
        button.up('navigationview').pop();
      });
    }else{
      toast('请输入您想分享的内容。');
    }

  },

  update: function(_p) {

    var _this = this;

    console.log(_p);


    _this.sns_data = _p.sns;
    _this.share_data = _p.data;


    var $ta = x$('ta_share_sina');


    if(_this.share_data.recruitmentTitle){
      $ta.setValue(_this.share_data.recruitmentTitle + '\nhttp://www.eyoudu.com');
    }



  }

});