/*
 * File: app/view/TopicReply.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.view.TopicReply', {
  extend: 'Ext.Container',

  requires: [
    'Ext.TitleBar',
    'Ext.Button',
    'Ext.dataview.DataView',
    'Ext.XTemplate'
  ],

  config: {
    cls: 'zjs',
    layout: 'card',
    items: [
      {
        xtype: 'titlebar',
        cls: 'zjs-bg-green',
        docked: 'top',
        ui: 'zjs',
        title: '跟帖回复',
        items: [
          {
            xtype: 'button',
            height: 30,
            itemId: 'mybutton23',
            ui: 'plain',
            width: 30,
            icon: '',
            iconCls: 'zjs-icon-back',
            text: 'back'
          }
        ]
      },
      {
        xtype: 'dataview',
        cls: 'zjs-listview-topic-reply',
        itemId: 'mydataview3',
        minHeight: 180,
        scrollable: 'vertical',
        disableSelection: true,
        itemTpl: [
          '<div class="li">',
          '  <div class="c">',
          '    <h4>{title}</h4>',
          '    <p> <span class="fl">赞：<em>{cc_zan}</em> 评论：<em>20</em></span> <span class="fr"><em>2014-01-14</em></span> </p>',
          '  </div>',
          '  <div class="i"> <span></span> </div>',
          '  <tpl if="badge &gt; 0">',
          '  <div class="b">',
          '    <span>{badge}</span>',
          '  </div>',
          '  </tpl>',
          '</div>',
          ''
        ],
        store: 'TopicReply'
      }
    ],
    listeners: [
      {
        fn: 'onMybutton23Tap',
        event: 'tap',
        delegate: '#mybutton23'
      },
      {
        fn: 'onMydataview2ItemTap1',
        event: 'itemtap',
        delegate: '#mydataview3'
      }
    ]
  },

  onMybutton23Tap: function(button, e, eOpts) {
    button.up('navigationview').pop();
  },

  onMydataview2ItemTap1: function(dataview, index, target, record, e, eOpts) {

    var item_data = record.data;


    //var page = Ext.create('ZJ02.view.InterviewNoticeDetail', {fullscreen: true});
    //dataview.up('navigationview').push(page);

  },

  initialize: function() {
    this.callParent();
  },

  update: function(_p) {

  },

  build_list: function(data) {
    var x$list = x$('list-home-search-result');


    if(data.length){
      x$list.removeCls('zj-list-no-data');
      x$list.setData(data);
    }else{
      x$list.addCls('zj-list-no-data');
      x$list.removeAll();
    }

    refresh_scroll(x$list);
  }

});