/*
 * File: app/model/optSchool.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ZJ02.model.optSchool', {
  extend: 'Ext.data.Model',

  requires: [
    'Ext.data.Field'
  ],

  config: {
    fields: [
      {
        name: 'schoolId'
      },
      {
        name: 'schoolname'
      },
      {
        name: 'num'
      },
      {
        name: 'iconImage'
      },
      {
        name: 'shortPinyin'
      },
      {
        name: 'longPinyin'
      },
      {
        name: 'currentNum'
      },
      {
        name: 'address'
      },
      {
        name: 'zipCode'
      },
      {
        name: 'phone'
      },
      {
        name: 'email'
      },
      {
        name: 'website'
      },
      {
        name: 'intro'
      },
      {
        name: 'busScope'
      },
      {
        name: 'details'
      },
      {
        name: 'provinceId'
      },
      {
        name: 'districtId'
      }
    ]
  }
});