/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
  models: [
    'city',
    'hpNav',
    'recruitment',
    'optFunctions',
    'optIndustry',
    'optSchool',
    'optSkill',
    'moreNav',
    'messageNav',
    'SubscribePosition',
    'Subscription',
    'InterviewNotice',
    'TopicReply',
    'UserCenterNav',
    'ResumeItem',
    'ApplyLog',
    'JobFavourite',
    'WhoSeeMe',
    'Company',
    'NestedData'
  ],
  stores: [
    'hpNav',
    'recruitment',
    'optFunctions',
    'optIndustry',
    'optSchool',
    'optSkill',
    'moreNav',
    'messageNav',
    'SubscribePosition',
    'Subscription',
    'InterviewNotice',
    'TopicReply',
    'UserCenterNav',
    'ResumeItem',
    'ApplyLog',
    'JobFavourite',
    'WhoSeeMe',
    'Company',
    'NestedDataIndustry',
    'NestedDataFunction',
    'NestedDataIndustry_sub3',
    'NestedCitys'
  ],
  views: [
    'BootSlider',
    'Home',
    'Login',
    'TabFrame',
    'NavTab1',
    'Register',
    'ResetPassword',
    'CampusTalk',
    'NavTab2',
    'NavTab3',
    'NavTab4',
    'NavTab5',
    'More',
    'PushSettings',
    'AccountBind',
    'Feedback',
    'AppIntroduction',
    'MyNotice',
    'RecruitmentDetail',
    'JobBookList',
    'JobBookApplyList',
    'InterviewNotice',
    'InterviewNoticeDetail',
    'TopicReply',
    'UserCenter',
    'ResumeCenter',
    'ResumePreview',
    'ApplyLog',
    'JobFavourite',
    'WhoSeeMe',
    'PublishedArticle',
    'PublishedArticleList',
    'RepliedArticleList',
    'ArticleFavourite',
    'ArticleCenter',
    'AcPerception',
    'AcResume',
    'AcInterview',
    'AcStaff',
    'AcSubmit',
    'AcDetail',
    'CampusTalkDetail',
    'CompanyMap',
    'CompanyDetail',
    'CompanyDetailIntro',
    'CompanyDetailPosition',
    'InternPosition',
    'InternPositionDetail',
    'PositionSubscribe',
    'PositionSubscribeByPosition',
    'PositionSubscribeByCompany',
    'PositionSubscribeByIndustry',
    'HomeSearchResult',
    'AppConfig',
    'Recruitment',
    'CompanyHot',
    'CompanyNear',
    'CityChooser',
    'AccountBindSinaWeibo',
    'PG_Message',
    'ShareFormSina',
    'ResumeCenterDetail',
    'PositionSubscribeByPositionSelectIndustry',
    'PositionSubscribeByPositionSelectFunc',
    'CityChooser_CNL'
  ],
  controllers: [
    'App'
  ],
  name: 'ZJ02',

  launch: function() {
    //Ext.create('ZJ02.view.TestTab', {fullscreen: true});
    //return;



    // platform
    if( Ext.os.name == 'iOS' ){
      _G.PLATFORM = 'ios';
    }else if( Ext.os.name == 'Android' ){
      _G.PLATFORM = 'android';
    }


    // Adjust toolbar height when running in iOS to fit with new iOS 7 style
    if ( Ext.os.is.iOS && Ext.os.version.major >= 7 ) {
      jQuery('body').addClass('x-ios-flat');
    }


    var last_view_version = get_s('last_view_version') || 0;
    var first_view = false;
    if( parseInt(last_view_version,10)<_G.VER ){
      first_view = true;
      set_s('last_view_version',_G.VER);
    }


    //disable for MIUI
    Ext.Msg.defaultAllowedConfig.showAnimation = false;
    Ext.Msg.defaultAllowedConfig.hideAnimation = false;


    //Ext.create('ZJ02.view.BootSlider', {fullscreen: true});


    if ( first_view ){
      Ext.create('ZJ02.view.BootSlider', {fullscreen: true});
      //Ext.create('ZJ02.view.Login', {fullscreen: true});
    }else{
      Ext.create('ZJ02.view.TabFrame', {fullscreen: true});
    }


    /*
    update_location(function(loc,status,geo){

    });
    */



    //版本更新检查
    window.setTimeout(function(){
        check_new_version(function(result,success){
          if(success){
            if(result){
              Ext.Msg.confirm('版本更新','发现新的版本，您需要更新吗？',function(confirmed){
                if( confirmed == 'yes' ){
                  window.open(result, '_system');
                }
              });
            }else{
            }
          }else{
          }
        },true);
    },10000);



    //根据ip获取地址
    window.setTimeout(function(){

      get_ip_location(function(result){

      });


    },1000);





    //提醒查询
    window.setTimeout(function(){
      alert_update();
    },10000);


    window.setInterval(function(){
      alert_update();
    },300000);






    window.gaPlugin = window.plugins.gaPlugin;
    gaPlugin.init(function(){
      gaPlugin.trackEvent( null, null, "App", "Launch", _G.PLATFORM, 1);
    }, null, "UA-50972675-1", 10);




  }

});
